apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: open-webui
data:
  config.json: |
    {
      "mcpServers": {
        "gitlab": {
          "command": "npx",
          "args": ["-y", "-p", "zod@3.23.8", "-p", "zod-to-json-schema@3.23.5", "-p", "@modelcontextprotocol/server-gitlab", "mcp-server-gitlab"]
        }
      }
    }
