apiVersion: v1
kind: Service
metadata:
  name: mcpo
  namespace: open-webui
spec:
  selector:
    app.kubernetes.io/name: mcpo
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
