apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-setup-config
  namespace: identity
data:
  CLUSTER_NAME: "kss"
  CLUSTER_DOMAIN: "kss.example.com"
  KEYCLOAK_URL: "https://auth.kss.example.com"
  API_SERVER: "https://kss-master.kss.example.com:6443"
  LOG_LEVEL: "info"
