apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/keycloak

patches:
  - target:
      kind: Keycloak
      name: broker-keycloak
    patch: |
      - op: replace
        path: /spec/hostname/hostname
        value: auth.simple-k8s.example.com
  - target:
      kind: Ingress
      name: broker-keycloak
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: auth.simple-k8s.example.com
      - op: replace
        path: /spec/rules/0/host
        value: auth.simple-k8s.example.com
