apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/globalpulse

patches:
  - target:
      kind: Ingress
      name: globalpulse
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: world.kss.example.com
      - op: replace
        path: /spec/rules/0/host
        value: world.kss.example.com
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1auth-signin
        value: "https://oauth2-proxy.kss.example.com/oauth2/start?rd=$scheme://$host$escaped_request_uri"
