#!/usr/bin/env bash
# Common library for all stage scripts
# Source this file at the top of every stage script:
#   source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

set -euo pipefail

# ─── Project Paths ────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IAC_DIR="${PROJECT_ROOT}/iac"
STAGES_DIR="${PROJECT_ROOT}/stages"
HELMFILE_DIR="${IAC_DIR}/helmfile"
KUSTOMIZE_DIR="${IAC_DIR}/kustomize"

# ─── Local Config (generated by generate-config.sh) ──────────────────────────

CONFIG_LOCAL="${STAGES_DIR}/lib/config-local.sh"
if [ -f "$CONFIG_LOCAL" ]; then
    source "$CONFIG_LOCAL"
else
    echo -e "\033[0;33mWARNING: $CONFIG_LOCAL not found. Run 'just generate-config' first.\033[0m" >&2
    # Fallback defaults so scripts don't crash immediately
    SUPPORT_VM_IP="${SUPPORT_VM_IP:-10.69.50.10}"
    SUPPORT_DOMAIN="${SUPPORT_DOMAIN:-support.example.com}"
    ROOT_DOMAIN="${ROOT_DOMAIN:-example.com}"
    BASE_DOMAIN="${BASE_DOMAIN:-example.com}"
    VAULT_URL="${VAULT_URL:-https://vault.support.example.com}"
    HARBOR_URL="${HARBOR_URL:-https://harbor.example.com}"
    HARBOR_REGISTRY="${HARBOR_REGISTRY:-harbor.example.com}"
    MINIO_URL="${MINIO_URL:-https://minio.support.example.com}"
    GITLAB_URL="${GITLAB_URL:-https://gitlab.support.example.com}"
    GITLAB_SSH_URL="${GITLAB_SSH_URL:-ssh://git@gitlab.support.example.com:2222}"
    GIT_REPO_URL="${GIT_REPO_URL:-ssh://git@gitlab.support.example.com:2222/infra/homelab.git}"
    KEYCLOAK_URL="${KEYCLOAK_URL:-https://idp.support.example.com}"
    TELEPORT_ADDR="${TELEPORT_ADDR:-teleport.support.example.com:3080}"
    PORTAL_PREFIX="${PORTAL_PREFIX:-portal.homelab}"
    LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-letsencrypt@example.com}"
    TARGET_REVISION="${TARGET_REVISION:-deploy}"
fi

# ─── Execution Helpers ────────────────────────────────────────────────────────

VAGRANT_SSH_KEY="~/.vagrant.d/ecdsa_private_key"

VAULT_KEYS_BACKUP="${IAC_DIR}/.vault-keys-backup.json"

# ─── Color Output ─────────────────────────────────────────────────────────────

BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()    { echo -e "${BLUE}$*${NC}"; }
success() { echo -e "${GREEN}$*${NC}"; }
error()   { echo -e "${RED}$*${NC}" >&2; }
warn()    { echo -e "${YELLOW}$*${NC}"; }
header()  { echo -e "\n${BLUE}=== $* ===${NC}"; }

# ─── Cluster Configuration ────────────────────────────────────────────────────

require_cluster() {
  if [[ -z "${KSS_CLUSTER:-}" ]]; then
    error "KSS_CLUSTER environment variable is not set."
    error "Set it to the cluster you want to operate on, e.g.:"
    error "  export KSS_CLUSTER=kss"
    error "  just cluster-status"
    exit 1
  fi
  local cluster_file="${IAC_DIR}/clusters/${KSS_CLUSTER}/cluster.yaml"
  if [[ ! -f "$cluster_file" ]]; then
    error "Cluster '${KSS_CLUSTER}' not found: $cluster_file does not exist"
    exit 1
  fi
}

# Read a value from the active cluster's cluster.yaml via yq
# Usage: cluster_yaml_val '.master.ip'
cluster_yaml_val() {
  local path="$1"
  yq -r "$path" "${IAC_DIR}/clusters/${KSS_CLUSTER}/cluster.yaml"
}

# Cluster-derived paths (only valid after require_cluster)
cluster_dir()     { echo "${IAC_DIR}/clusters/${KSS_CLUSTER}"; }
cluster_gen_dir() { echo "${IAC_DIR}/clusters/${KSS_CLUSTER}/generated"; }

# Load cluster variables into shell (call after require_cluster)
load_cluster_vars() {
  CLUSTER_NAME="$(cluster_yaml_val '.name')"
  CLUSTER_DOMAIN="$(cluster_yaml_val '.domain')"
  CLUSTER_MASTER_IP="$(cluster_yaml_val '.master.ip')"
  CLUSTER_CNI="$(cluster_yaml_val '.cni // "default"')"
  CLUSTER_HELMFILE_ENV="$(cluster_yaml_val '.helmfile_env // "default"')"
  CLUSTER_VAULT_AUTH_MOUNT="$(cluster_yaml_val '.vault.auth_mount')"
  CLUSTER_VAULT_NAMESPACE="$(cluster_yaml_val '.vault.namespace // ""')"
  MASTER_VM="${CLUSTER_NAME}-master"

  CLUSTER_WORKER_COUNT="$(yq '.workers | length' "${IAC_DIR}/clusters/${KSS_CLUSTER}/cluster.yaml")"

  # Build worker IP and name arrays
  CLUSTER_WORKER_IPS=()
  CLUSTER_WORKER_NAMES=()
  CLUSTER_WORKER_VMS=()
  for i in $(seq 0 $((CLUSTER_WORKER_COUNT - 1))); do
    local wip
    wip="$(cluster_yaml_val ".workers[$i].ip")"
    local wname
    wname="$(cluster_yaml_val ".workers[$i].name")"
    CLUSTER_WORKER_IPS+=("$wip")
    CLUSTER_WORKER_NAMES+=("$wname")
    CLUSTER_WORKER_VMS+=("${CLUSTER_NAME}-${wname}")
  done

  CLUSTER_ALL_VMS="${MASTER_VM} ${CLUSTER_WORKER_VMS[*]}"

}

# ─── VM Execution Helpers ────────────────────────────────────────────────────
# All commands run directly on the hypervisor where vagrant/libvirt live.

# Vagrant state (.vagrant/) lives in the main project root, not in worktrees.
# Resolve the main worktree so vagrant can always find its VMs.
VAGRANT_IAC_DIR="$(git -C "${PROJECT_ROOT}" worktree list --porcelain | head -1 | sed 's/^worktree //')/iac"

# Run vagrant command (in main project iac/ directory)
vagrant_cmd() {
  (cd "${VAGRANT_IAC_DIR}" && vagrant "$@")
}

# Run vagrant ssh to a VM and execute a command
vagrant_ssh() {
  local vm="$1"
  shift
  vagrant_cmd ssh "${vm}" -c "$*"
}

# SSH directly to a VM via its IP
ssh_vm() {
  local ip="$1"
  shift
  ssh -o StrictHostKeyChecking=no -i "${VAGRANT_SSH_KEY}" "vagrant@${ip}" "$*"
}

# rsync files to a VM
rsync_to_vm() {
  local ip="$1"
  local src="$2"
  local dst="$3"
  rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ${VAGRANT_SSH_KEY}" "${src}" "vagrant@${ip}:${dst}"
}

# ─── Validation Helpers ───────────────────────────────────────────────────────

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" &>/dev/null; then
    error "Required command not found: $cmd"
    exit 1
  fi
}

require_kubeconfig() {
  if [[ -z "${KUBECONFIG:-}" ]]; then
    error "KUBECONFIG not set"
    error "Run: export KUBECONFIG=~/.kube/config-${KSS_CLUSTER}"
    exit 1
  fi
}

require_vault_token() {
  if [[ -z "${VAULT_TOKEN:-}" ]]; then
    error "VAULT_TOKEN not set"
    error "Run: export VAULT_TOKEN=\$(just vault-token)"
    exit 1
  fi
}

require_vault_addr() {
  if [[ -z "${VAULT_ADDR:-}" ]]; then
    error "VAULT_ADDR not set"
    error "Run: export VAULT_ADDR=\$VAULT_URL"
    exit 1
  fi
}

require_vault_keys_backup() {
  if [[ ! -f "${VAULT_KEYS_BACKUP}" ]]; then
    error "Vault keys backup not found at ${VAULT_KEYS_BACKUP}"
    error "Run: just vault-backup"
    exit 1
  fi
}

# ─── Confirmation Helpers ────────────────────────────────────────────────────

# Parse --yes / -y flag from script arguments.
# Call early: parse_yes_flag "$@"
# Sets SKIP_CONFIRM=true if found. Remaining args in REMAINING_ARGS array.
parse_yes_flag() {
  SKIP_CONFIRM=false
  REMAINING_ARGS=()
  for arg in "$@"; do
    case "$arg" in
      --yes|-y) SKIP_CONFIRM=true ;;
      *) REMAINING_ARGS+=("$arg") ;;
    esac
  done
}

# Prompt the user for confirmation before a dangerous action.
# Usage: confirm_action "message" ["danger"]
#   - "danger" level requires typing "yes"; default uses y/N prompt
# Respects SKIP_CONFIRM=true to skip the prompt.
# Exits with code 1 if the user declines.
confirm_action() {
  local message="$1"
  local level="${2:-warn}"

  if [[ "${SKIP_CONFIRM:-false}" == "true" ]]; then
    return 0
  fi

  echo ""
  if [[ "$level" == "danger" ]]; then
    error ">>> ${message}"
    echo ""
    read -rp "Type 'yes' to confirm: " REPLY
    echo ""
    if [[ "$REPLY" != "yes" ]]; then
      info "Cancelled."
      exit 1
    fi
  else
    warn ">>> ${message}"
    read -rp "Continue? [y/N] " -n 1 REPLY
    echo ""
    if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
      info "Cancelled."
      exit 1
    fi
  fi
}

# ─── Kubectl / Helmfile Wrappers ──────────────────────────────────────────────

kube_cmd() {
  require_kubeconfig
  kubectl "$@"
}

helmfile_cmd() {
  require_kubeconfig
  cd "${HELMFILE_DIR}" && helmfile \
    --state-values-file "$(cluster_gen_dir)/helmfile-values.yaml" \
    "$@"
}
