{
 "title": "Loki Logs",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Error Rate by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({namespace=~\"$namespace\"} |~ \"(?i)(error|err|panic|fatal|exception)\" [$__interval]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Log Lines",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}"
    }
   ]
  }
 ]
}