apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Monitoring namespace ExternalSecrets
# - Grafana admin password from Vault
# - Grafana OIDC client secret from Vault
# - Loki MinIO credentials from Vault

resources:
  - grafana-admin-secret.yaml
  - grafana-oidc-secret.yaml
  - loki-minio-secret.yaml
  - prometheus-rules.yaml
  - grafana-dashboard-trivy.yaml
  - grafana-dashboard-loki.yaml
  - grafana-dashboard-gatekeeper.yaml
  - gatekeeper-metrics.yaml
