apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dependency-track-db-credentials
  namespace: dependency-track
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dependency-track-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        postgres-password: "{{ .postgresPassword }}"
        database-url: "jdbc:postgresql://dependency-track-db-rw.dependency-track.svc:5432/dependency-track?user={{ .username }}&password={{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: dependency-track/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dependency-track/db-credentials
        property: password
    - secretKey: postgresPassword
      remoteRef:
        key: dependency-track/db-credentials
        property: postgres-password
