apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dependency-track-oidc
  namespace: dependency-track
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dependency-track-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: keycloak/dependency-track-client
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: keycloak/dependency-track-client
        property: client-secret
