apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/jit-elevation

patches:
  - target:
      kind: ConfigMap
      name: jit-config
    patch: |
      - op: replace
        path: /data/KEYCLOAK_URL
        value: "https://auth.kss.example.com"
  - target:
      kind: Ingress
      name: jit-elevation
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: jit.kss.example.com
      - op: replace
        path: /spec/rules/0/host
        value: jit.kss.example.com
