apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: bootstrap
  sources:
    - repoURL: https://github.com/example-user/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: "1.19.0"
      helm:
        valueFiles:
          - $values/iac/argocd/values/kcs/cilium.yaml
        parameters:
          - name: k8sServiceHost
            value: kcs-master.mesh-k8s.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - SkipDryRunOnMissingResource=true
