apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: bootstrap
  source:
    repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
    targetRevision: main
    path: iac/argocd/clusters/kcs/kustomize/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
