apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: bootstrap
  sources:
    - repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: "1.28.*"
      helm:
        valueFiles:
          - $values/iac/argocd/values/kcs/istio-istiod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
