apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: identity
  source:
    repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
    targetRevision: main
    path: iac/argocd/clusters/kcs/kustomize/oauth2-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
