apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ziti-router-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: bootstrap
  source:
    repoURL: https://github.com/example-user/homelab.git
    targetRevision: main
    path: iac/argocd/clusters/kcs/kustomize/ziti-router
  destination:
    server: https://kubernetes.default.svc
    namespace: ziti-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
