{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.version }}

  bootstrap:
    initdb:
      database: {{ .Values.postgres.database | default .Release.Name }}

  storage:
    size: {{ .Values.postgres.size }}

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
{{- end }}
