{{- range $secret := .Values.vaultSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $secret.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ $.Release.Name }}-{{ $secret.name }}
    creationPolicy: Owner
  {{- if $secret.keys }}
  data:
    {{- range $envVar, $vaultProp := $secret.keys }}
    - secretKey: {{ $envVar }}
      remoteRef:
        key: {{ $secret.path }}
        property: {{ $vaultProp }}
    {{- end }}
  {{- else }}
  dataFrom:
    - extract:
        key: {{ $secret.path }}
  {{- end }}
{{- end }}
