#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
require_cluster
load_cluster_vars
require_kubeconfig
require_vault_keys_backup

GEN_DIR="$(cluster_gen_dir)"
VAULT_ROOT_TOKEN=$(jq -r '.root_token' "${VAULT_KEYS_BACKUP}")

# Build namespace header if configured
NS_HEADER=""
if [[ -n "${CLUSTER_VAULT_NAMESPACE}" ]]; then
  NS_HEADER="-H X-Vault-Namespace:${CLUSTER_VAULT_NAMESPACE}"
  info "Using Vault namespace: ${CLUSTER_VAULT_NAMESPACE}"
fi

# ─── Helper: seed a Vault secret if it doesn't exist ─────────────────────────
# Usage: vault_seed <path> <json-data>
vault_seed() {
  local path="$1" data="$2"
  local check
  check=$(curl -sk -o /dev/null -w "%{http_code}" \
    -H "X-Vault-Token: ${VAULT_ROOT_TOKEN}" \
    ${NS_HEADER} \
    "${VAULT_URL}/v1/secret/data/${path}")
  if [[ "$check" == "200" ]]; then
    info "Vault secret/${path} already exists"
    return 0
  fi
  info "Seeding secret/${path} into Vault..."
  local result http_code
  result=$(curl -sk -w "\n%{http_code}" -X POST \
    -H "X-Vault-Token: ${VAULT_ROOT_TOKEN}" \
    ${NS_HEADER} \
    -H "Content-Type: application/json" \
    -d "$data" \
    "${VAULT_URL}/v1/secret/data/${path}")
  http_code=$(echo "$result" | tail -1)
  if [[ "$http_code" == "200" || "$http_code" == "204" ]]; then
    success "Stored secret/${path} in Vault"
  else
    error "Failed to store secret/${path} in Vault (HTTP ${http_code})"
    echo "$result" | head -n -1
    exit 1
  fi
}

# ─── Seed Vault secrets from support VM ──────────────────────────────────────
# All bootstrap secrets are seeded here. Each is idempotent (skipped if exists).
#
# Source credentials:
#   - Cloudflare API token: SOPS-encrypted, decrypted on support VM at /run/secrets/cloudflare_api_token
#   - Harbor admin password: generated by Harbor, stored at /etc/harbor/admin_password on support VM
#   - Keycloak DB credentials: randomly generated on first seed
#   - OAuth2-Proxy cookie secret: randomly generated on first seed

# 1. Cloudflare API token (consumed by cert-manager + external-dns ExternalSecrets)
#    SOPS stores it as "CLOUDFLARE_DNS_API_TOKEN=<token>" — strip the key= prefix.
CF_RAW=$(ssh_vm "${SUPPORT_VM_IP}" 'sudo cat /run/secrets/cloudflare_api_token') || {
  error "Could not fetch Cloudflare API token from support VM"
  error "Ensure support VM is running and SOPS secrets are decrypted"
  exit 1
}
CF_TOKEN="${CF_RAW#*=}"
if [[ -z "$CF_TOKEN" ]]; then
  error "Cloudflare API token is empty"
  exit 1
fi
vault_seed "cloudflare" "$(jq -n --arg token "$CF_TOKEN" '{data: {"api-token": $token}}')"

# 2. Harbor admin credentials (consumed by harbor-pull-secret ExternalSecrets)
HARBOR_PASS=$(ssh_vm "${SUPPORT_VM_IP}" 'sudo cat /etc/harbor/admin_password') || {
  error "Could not fetch Harbor admin password from support VM"
  error "Ensure support VM is running and /etc/harbor/admin_password exists"
  exit 1
}
if [[ -z "$HARBOR_PASS" ]]; then
  error "Harbor admin password is empty"
  exit 1
fi
vault_seed "harbor/admin" "$(jq -n --arg user "admin" --arg pass "$HARBOR_PASS" --arg url "https://harbor.support.example.com" \
  '{data: {username: $user, password: $pass, url: $url}}')"

# 3. Keycloak DB credentials (consumed by keycloak ExternalSecret)
vault_seed "keycloak/db-credentials" "$(jq -n \
  --arg user "keycloak" \
  --arg pass "$(openssl rand -base64 32 | tr -d '=/+' | head -c 32)" \
  --arg admin "$(openssl rand -base64 32 | tr -d '=/+' | head -c 32)" \
  '{data: {username: $user, password: $pass, "admin-password": $admin}}')"

# 4. OAuth2-Proxy cookie secret (consumed by oauth2-proxy ExternalSecret)
vault_seed "oauth2-proxy" "$(jq -n \
  --arg secret "$(openssl rand -hex 16)" \
  '{data: {"cookie-secret": $secret}}')"

# ─── Apply ExternalSecrets ───────────────────────────────────────────────────

info "Waiting for ExternalSecret CRDs to be established..."
for crd in clustersecretstores.external-secrets.io externalsecrets.external-secrets.io; do
  CRD_READY=false
  for i in $(seq 1 60); do
    if kubectl wait crd/"$crd" --for=condition=Established --timeout=2s >/dev/null 2>&1; then
      CRD_READY=true
      break
    fi
    sleep 2
  done
  if [[ "$CRD_READY" != "true" ]]; then
    error "ExternalSecret CRD $crd not established after 120s"
    exit 1
  fi
done

info "Waiting for external-secrets webhook to be ready..."
kubectl -n external-secrets rollout status deployment/external-secrets-webhook --timeout=120s

info "Ensuring required namespaces exist..."
for ns in cert-manager external-dns argocd keycloak monitoring longhorn-system trivy-system identity; do
  kubectl create namespace "$ns" 2>/dev/null || true
done

info "Invalidating kubectl discovery cache..."
rm -rf ~/.kube/cache

info "Applying ClusterSecretStore and ExternalSecrets (${KSS_CLUSTER})..."
kubectl apply -k "${GEN_DIR}/kustomize/external-secrets/"

info "Waiting for ExternalSecrets to sync..."
ALL_SYNCED=true
for ES in "cloudflare-api-token:cert-manager" "cloudflare-api-token:external-dns" "keycloak-db-credentials:keycloak" "argocd-oidc-secret:argocd"; do
  NAME="${ES%%:*}"
  NS="${ES##*:}"
  STATUS=""
  for i in $(seq 1 30); do
    STATUS=$(kubectl get externalsecret "$NAME" -n "$NS" -o jsonpath='{.status.conditions[0].reason}' 2>/dev/null) || true
    if [[ "$STATUS" == "SecretSynced" ]]; then break; fi
    sleep 2
  done
  if [[ "$STATUS" != "SecretSynced" ]]; then
    warn "ExternalSecret $NAME in $NS not synced (status: ${STATUS:-unknown})"
    ALL_SYNCED=false
  fi
done
if [[ "$ALL_SYNCED" == "true" ]]; then
  success "All ExternalSecrets synced from Vault"
else
  warn "Some ExternalSecrets not yet synced. Check ClusterSecretStore and Vault connectivity."
fi

info "Applying Harbor imagePullSecrets (${KSS_CLUSTER})..."
kubectl apply -k "${GEN_DIR}/kustomize/harbor/"

success "Secrets and Harbor pull secrets applied"
