#!/usr/bin/env bash
# Bootstrap Harbor: download, configure, and install
#
# NOTE: This script is SUPERSEDED by harbor.nix auto-setup service.
# The harbor-setup systemd service now handles:
# - Downloading Harbor offline installer on first boot
# - Generating harbor.yml with all required configuration
# - Auto-generating admin password and secret keys
# - Running the Harbor installer with Trivy
# - Optionally configuring MinIO S3 backend if credentials exist
#
# This script is kept for reference and manual operations only.
# Run this AFTER MinIO and certificates are set up (if not using auto-setup)

set -euo pipefail

HARBOR_VERSION="${HARBOR_VERSION:-v2.11.0}"
HARBOR_DIR="/opt/harbor"
HARBOR_DATA_DIR="/var/lib/harbor"
HARBOR_INSTALLER_URL="https://github.com/goharbor/harbor/releases/download/${HARBOR_VERSION}/harbor-offline-installer-${HARBOR_VERSION}.tgz"

echo "==> Harbor Bootstrap Script"
echo "    Version: ${HARBOR_VERSION}"

# Check if Harbor is already installed
if [ -f "${HARBOR_DIR}/docker-compose.yml" ]; then
    echo "==> Harbor is already installed at ${HARBOR_DIR}"
    echo "    To reinstall, run: sudo rm -rf ${HARBOR_DIR}"
    echo "    Then re-run this script"
    exit 0
fi

# Check prerequisites
echo "==> Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed"
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo "ERROR: docker-compose is not installed"
    exit 1
fi

# Load MinIO credentials if available
MINIO_CREDS="/etc/minio/credentials"
if [ -f "${MINIO_CREDS}" ]; then
    source "${MINIO_CREDS}"
    echo "    MinIO credentials loaded"
else
    echo "WARNING: MinIO credentials not found at ${MINIO_CREDS}"
    echo "         Harbor will use local storage"
fi

# Create directories
sudo mkdir -p "${HARBOR_DIR}"
sudo mkdir -p "${HARBOR_DATA_DIR}"

# Download Harbor
echo "==> Downloading Harbor ${HARBOR_VERSION}..."
cd /tmp
curl -L "${HARBOR_INSTALLER_URL}" -o harbor-installer.tgz

echo "==> Extracting Harbor..."
tar xzf harbor-installer.tgz
sudo mv harbor/* "${HARBOR_DIR}/"
rm -rf harbor harbor-installer.tgz

# Generate harbor.yml from template
echo "==> Generating harbor.yml configuration..."

# Generate Harbor admin password if not exists
HARBOR_ADMIN_PASSWORD_FILE="/etc/harbor/admin_password"
if [ ! -f "${HARBOR_ADMIN_PASSWORD_FILE}" ]; then
    sudo mkdir -p /etc/harbor
    HARBOR_ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo "${HARBOR_ADMIN_PASSWORD}" | sudo tee "${HARBOR_ADMIN_PASSWORD_FILE}" > /dev/null
    sudo chmod 600 "${HARBOR_ADMIN_PASSWORD_FILE}"
else
    HARBOR_ADMIN_PASSWORD=$(sudo cat "${HARBOR_ADMIN_PASSWORD_FILE}")
fi

# Generate secret key
HARBOR_SECRET_KEY=$(openssl rand -hex 16)

sudo tee "${HARBOR_DIR}/harbor.yml" > /dev/null << EOF
# Harbor Configuration
# Generated by bootstrap-harbor.sh

hostname: harbor.example.com

# HTTP only - Nginx handles TLS termination
http:
  port: 8080

# Disable HTTPS - using Nginx reverse proxy
# https:
#   port: 443
#   certificate: /your/certificate/path
#   private_key: /your/private/key/path

# Harbor admin password
harbor_admin_password: ${HARBOR_ADMIN_PASSWORD}

# Database configuration (internal PostgreSQL)
database:
  password: $(openssl rand -hex 16)
  max_idle_conns: 50
  max_open_conns: 100

# Data volume
data_volume: ${HARBOR_DATA_DIR}

# Trivy vulnerability scanner
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false

# Job service
jobservice:
  max_job_workers: 10

# Notification
notification:
  webhook_job_max_retry: 3

# Logging
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

# Internal secret key for encryption
secret_key: ${HARBOR_SECRET_KEY}

# Proxy settings (if needed)
# proxy:
#   http_proxy:
#   https_proxy:
#   no_proxy:

# External URL (how users access Harbor)
external_url: https://harbor.example.com

# Metrics (for Prometheus scraping)
metric:
  enabled: true
  port: 9090
  path: /metrics
EOF

# Add storage configuration if MinIO is available
if [ -n "${MINIO_ROOT_USER:-}" ] && [ -n "${MINIO_ROOT_PASSWORD:-}" ]; then
    echo "==> Configuring S3 storage backend (MinIO)..."

    sudo tee -a "${HARBOR_DIR}/harbor.yml" > /dev/null << EOF

# Storage backend - MinIO S3
storage_service:
  s3:
    accesskey: ${MINIO_ROOT_USER}
    secretkey: ${MINIO_ROOT_PASSWORD}
    region: us-east-1
    bucket: harbor
    regionendpoint: http://127.0.0.1:9000
    secure: false
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
EOF
fi

# Run Harbor installer
echo "==> Running Harbor installer..."
cd "${HARBOR_DIR}"
sudo ./install.sh --with-trivy

echo ""
echo "==> Harbor installation complete!"
echo ""
echo "    URL: https://harbor.example.com"
echo "    Username: admin"
echo "    Password: $(sudo cat ${HARBOR_ADMIN_PASSWORD_FILE})"
echo ""
echo "    Password stored in: ${HARBOR_ADMIN_PASSWORD_FILE}"
echo ""
echo "    To configure Docker to use Harbor:"
echo "    1. Add CA cert to system trust store"
echo "    2. docker login harbor.example.com"
echo ""
echo "    To set up proxy caches for Docker Hub, Quay.io, etc.:"
echo "    1. Go to Administration > Registries > + New Endpoint"
echo "    2. Add Docker Hub, Quay.io, etc."
echo "    3. Go to Projects > + New Project > Create as proxy cache"
