apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: kube-public
data:
  CLUSTER_NAME: "CLUSTER_NAME"
  CLUSTER_DOMAIN: "CLUSTER_DOMAIN"
  ANNOTATION_PREFIX: "portal.homelab/"
  LOG_LEVEL: "info"
