apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Headlamp namespace ExternalSecrets
# - OIDC client secret from Vault for Headlamp native OIDC auth

resources:
  - headlamp-oidc-secret.yaml
