apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/globalpulse

patches:
  # Delete Ingress on kcs (uses Gateway API HTTPRoute instead)
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: globalpulse
        namespace: globalpulse
      $patch: delete
