apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/headlamp

patches:
  # Patch issuerURL for kcs cluster Keycloak
  - target:
      kind: ExternalSecret
      name: headlamp-oidc
    patch: |
      - op: replace
        path: /spec/target/template/data/OIDC_ISSUER_URL
        value: "https://auth.mesh-k8s.example.com/realms/broker"
