{{- $ctx := (ds "ctx") -}}
# Auto-generated by generate-cluster.sh — do not edit
# Per-cluster chart values for {{ $ctx.computed.name }}

# Git repository
repoURL: "{{ $ctx.config.gitRepoUrl }}"
targetRevision: {{ $ctx.config.targetRevision }}

# Cluster identity
clusterName: {{ $ctx.computed.name }}
clusterDomain: "{{ $ctx.computed.domain }}"

# Domains
supportDomain: "{{ $ctx.config.supportDomain }}"
rootDomain: "{{ $ctx.computed.rootDomain }}"
harborRegistry: "{{ $ctx.config.harborRegistry }}"
gitlabUrl: "https://gitlab.{{ $ctx.config.supportDomain }}"
gitlabSshUrl: "ssh://git@gitlab.{{ $ctx.config.supportDomain }}:2222"
portalPrefix: "{{ $ctx.config.portalPrefix }}"
letsencryptEmail: "{{ $ctx.config.letsencryptEmail }}"

# Cluster type flags
cni: {{ $ctx.computed.cni }}
helmfileEnv: {{ $ctx.computed.helmfileEnv }}
oidcEnabled: {{ $ctx.computed.oidcEnabled }}

# Master node
master:
  fqdn: "{{ $ctx.computed.name }}-master.{{ $ctx.computed.domain }}"

# Networking
loadBalancer:
  cidr: "{{ $ctx.cluster.loadbalancer.cidr }}"
bgp:
  localAsn: {{ $ctx.cluster.bgp.asn }}
  peerAsn: 64512
  peerAddress: "10.69.50.1"

# Vault
vault:
  server: "{{ $ctx.config.vaultUrl }}"
  namespace: "{{ $ctx.computed.vaultNamespace }}"
  authMount: {{ $ctx.computed.vaultAuthMount }}

# OIDC
oidc:
  issuerUrl: "{{ $ctx.computed.oidcIssuerUrl }}"
  clientId: {{ $ctx.cluster.oidc.client_id }}

# Optional applications
apps:
  openWebui: {{ $ctx.apps.openWebui }}
  openclaw: {{ $ctx.apps.openclaw }}
  globalpulse: {{ $ctx.apps.globalpulse }}
  kiali: {{ $ctx.apps.kiali }}
