apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: bootstrap
  source:
    repoURL: __REPO_URL__
    targetRevision: __TARGET_REVISION__
    path: iac/argocd/clusters/__CLUSTER_NAME__/kustomize/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jqPathExpressions:
        - .spec.listeners[].tls.certificateRefs[].group
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[]
        - .spec.rules[].backendRefs[]
        - .spec.rules[].matches
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
