apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: applications
  source:
    repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
    targetRevision: main
    path: iac/argocd/clusters/kss/kustomize/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
