apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: applications
  source:
    repoURL: https://github.com/example-user/homelab.git
    targetRevision: main
    path: iac/argocd/clusters/kss/kustomize/portal
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
