# ArgoCD — kss cluster overrides
server:
  ingress:
    hostname: argocd.simple-k8s.example.com

configs:
  cm:
    url: "https://argocd.simple-k8s.example.com"
    oidc.config: |
      name: Keycloak
      issuer: https://auth.simple-k8s.example.com/realms/broker
      clientID: argocd
      clientSecret: $argocd-oidc-secret:client-secret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
