# kube-prometheus-stack — kss cluster overrides
grafana:
  ingress:
    hosts:
      - grafana.simple-k8s.example.com
    tls:
      - secretName: wildcard-simple-k8s.example.com-tls
        hosts:
          - grafana.simple-k8s.example.com
  grafana.ini:
    server:
      root_url: "https://grafana.simple-k8s.example.com"
    auth.generic_oauth:
      auth_url: "https://auth.simple-k8s.example.com/realms/broker/protocol/openid-connect/auth"
      token_url: "https://auth.simple-k8s.example.com/realms/broker/protocol/openid-connect/token"
      api_url: "https://auth.simple-k8s.example.com/realms/broker/protocol/openid-connect/userinfo"
