# OAuth2-Proxy — kss cluster overrides
extraArgs:
  oidc-issuer-url: "https://auth.simple-k8s.example.com/realms/broker"
  cookie-domain: ".simple-k8s.example.com"
  whitelist-domain: ".simple-k8s.example.com"
  redirect-url: "https://oauth2-proxy.simple-k8s.example.com/oauth2/callback"

ingress:
  hosts:
    - oauth2-proxy.simple-k8s.example.com
  tls:
    - secretName: oauth2-proxy-tls
      hosts:
        - oauth2-proxy.simple-k8s.example.com
