ingress:
  enabled: true
  class: nginx
  annotations:
    portal.example.com/name: "Open WebUI"
    portal.example.com/icon: "chat"
  host: chat.kss.example.com
  tls: true
  existingSecret: wildcard-kss-example-com-tls

sso:
  oidc:
    providerUrl: "https://auth.kss.example.com/realms/broker/.well-known/openid-configuration"
