# SPIRE — kss cluster overrides
global:
  spire:
    trustDomain: simple-k8s.example.com
    clusterName: kss

spire-server:
  oidcDiscoveryProvider:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - spire-oidc.simple-k8s.example.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: spire-oidc-tls
          hosts:
            - spire-oidc.simple-k8s.example.com
