# kss cluster teleport-kube-agent overrides

kubeClusterName: "kss"

labels:
  env: homelab
  cluster: kss

apps:
  - name: "grafana-kss"
    uri: "http://grafana.monitoring.svc.cluster.local:3000"
    labels:
      env: homelab
      cluster: kss
  - name: "argocd-kss"
    uri: "https://argocd-server.argocd.svc.cluster.local:443"
    insecure_skip_verify: true
    labels:
      env: homelab
      cluster: kss
  - name: "headlamp-kss"
    uri: "http://headlamp.headlamp.svc.cluster.local:80"
    labels:
      env: homelab
      cluster: kss
