#!/usr/bin/env bash
# Generate local configuration from config.yaml
#
# Reads config.yaml and produces ONLY gitignored files:
#   - stages/lib/config-local.sh                       (shell variables)
#   - iac/provision/nix/supporting-systems/generated-config.nix
#   - tofu/environments/*/terraform.tfvars              (OpenTofu variables)
#   - tofu/environments/*/backend.tf                    (MinIO S3 backend)
#   - .push-guard                                       (pre-push hook patterns)
#
# Also updates the ONLY tracked files that change:
#   - iac/clusters/*/cluster.yaml                       (domain + OIDC URLs)
#
# Usage: ./scripts/generate-config.sh [--check]
#   --check: verify config.yaml exists without generating

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/config.yaml"

# ─── Preflight ───────────────────────────────────────────────────────────────

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE not found."
    echo "Copy config.yaml.example to config.yaml and fill in your values:"
    echo "  cp config.yaml.example config.yaml"
    exit 1
fi

if ! command -v yq &>/dev/null; then
    echo "ERROR: yq is required but not found. Run: nix develop"
    exit 1
fi

if [ "${1:-}" = "--check" ]; then
    echo "config.yaml found and valid."
    exit 0
fi

# ─── Read config.yaml ────────────────────────────────────────────────────────

cfg() { yq -r "$1" "$CONFIG_FILE"; }

# sed-based YAML value replacement — preserves comments and formatting
yaml_sed_set() {
    local file="$1" key="$2" value="$3"
    sed -i "s|^\(\s*${key}:\s*\).*|\1${value}|" "$file"
}

ROOT_DOMAIN=$(cfg '.domains.root')
BASE_DOMAIN=$(cfg '.domains.base')
SUPPORT_PREFIX=$(cfg '.domains.support_prefix')
ZITI_DOMAIN=$(cfg '.domains.ziti')

HYPERVISOR=$(cfg '.hosts.hypervisor')
REMOTE_PROJECT_DIR=$(cfg '.hosts.remote_project_dir')

SUPPORT_IP=$(cfg '.support.ip')
TELEPORT_CLUSTER_NAME=$(cfg '.support.teleport_cluster_name')

ADMIN_EMAIL=$(cfg '.identity.admin_email')

NFS_ALLOWED_NETWORK=$(cfg '.network.nfs_allowed_network')

GIT_PROJECT_NAME=$(cfg '.git.project_name')
GITHUB_ORG=$(cfg '.git.github_org')

# ─── Derived values ──────────────────────────────────────────────────────────

SUPPORT_DOMAIN="${SUPPORT_PREFIX}.${BASE_DOMAIN}"
VAULT_URL="https://vault.${SUPPORT_DOMAIN}"
HARBOR_URL="https://harbor.${SUPPORT_DOMAIN}"
HARBOR_REGISTRY="harbor.${SUPPORT_DOMAIN}"
MINIO_URL="https://minio.${SUPPORT_DOMAIN}"
GITLAB_URL="https://gitlab.${SUPPORT_DOMAIN}"
GITLAB_SSH_URL="ssh://git@gitlab.${SUPPORT_DOMAIN}:2222"
GIT_REPO_URL="ssh://git@gitlab.${SUPPORT_DOMAIN}:2222/infra/${GIT_PROJECT_NAME}.git"
KEYCLOAK_URL="https://idp.${SUPPORT_DOMAIN}"
TELEPORT_ADDR="teleport.${SUPPORT_DOMAIN}:3080"
LETSENCRYPT_EMAIL="letsencrypt@${ROOT_DOMAIN}"
PORTAL_PREFIX="portal.${BASE_DOMAIN}"
GITLAB_SSH_HOST="[gitlab.${SUPPORT_DOMAIN}]:2222"
TARGET_REVISION="deploy"

echo "Generating config from $CONFIG_FILE..."
echo "  Root domain:    $ROOT_DOMAIN"
echo "  Base domain:    $BASE_DOMAIN"
echo "  Support domain: $SUPPORT_DOMAIN"

# ─── Helper: discover clusters ────────────────────────────────────────────────

get_clusters() {
    local clusters=()
    for dir in "$PROJECT_ROOT"/iac/clusters/*/; do
        if [ -f "${dir}cluster.yaml" ]; then
            clusters+=("$(basename "$dir")")
        fi
    done
    echo "${clusters[@]}"
}

cluster_domain() { echo "${1}.${BASE_DOMAIN}"; }

# ============================================================================
# 1. Generate stages/lib/config-local.sh
# ============================================================================
echo "  Generating stages/lib/config-local.sh..."
cat > "$PROJECT_ROOT/stages/lib/config-local.sh" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml

REMOTE_HOST="$HYPERVISOR"
REMOTE_PROJECT_DIR="\$HOME/$(echo "$REMOTE_PROJECT_DIR" | sed 's|^~/||')"
SUPPORT_VM_IP="$SUPPORT_IP"
SUPPORT_DOMAIN="$SUPPORT_DOMAIN"
ROOT_DOMAIN="$ROOT_DOMAIN"
BASE_DOMAIN="$BASE_DOMAIN"
VAULT_URL="$VAULT_URL"
HARBOR_URL="$HARBOR_URL"
HARBOR_REGISTRY="$HARBOR_REGISTRY"
MINIO_URL="$MINIO_URL"
GITLAB_URL="$GITLAB_URL"
GITLAB_SSH_URL="$GITLAB_SSH_URL"
GIT_REPO_URL="$GIT_REPO_URL"
KEYCLOAK_URL="$KEYCLOAK_URL"
TELEPORT_ADDR="$TELEPORT_ADDR"
PORTAL_PREFIX="$PORTAL_PREFIX"
LETSENCRYPT_EMAIL="$LETSENCRYPT_EMAIL"
SUPPORT_PREFIX="$SUPPORT_PREFIX"
TARGET_REVISION="$TARGET_REVISION"
EOF

# ============================================================================
# 2. Generate NixOS config
# ============================================================================
echo "  Generating generated-config.nix..."
cat > "$PROJECT_ROOT/iac/provision/nix/supporting-systems/generated-config.nix" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml
{
  domain = "${SUPPORT_DOMAIN}";
  rootDomain = "${ROOT_DOMAIN}";
  baseDomain = "${BASE_DOMAIN}";
  supportPrefix = "${SUPPORT_PREFIX}";
  zitiDomain = "${ZITI_DOMAIN}";
  adminEmail = "${ADMIN_EMAIL}";
  supportIp = "${SUPPORT_IP}";
  teleportClusterName = "${TELEPORT_CLUSTER_NAME}";
  githubOrg = "${GITHUB_ORG}";
  gitlabSshHost = "${GITLAB_SSH_HOST}";
  nfsAllowedNetwork = "${NFS_ALLOWED_NETWORK}";
}
EOF

# ============================================================================
# 3. Update cluster.yaml files (only tracked file modification)
# ============================================================================
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    CLUSTER_YAML="$PROJECT_ROOT/iac/clusters/$CLUSTER/cluster.yaml"

    echo "  Updating $CLUSTER/cluster.yaml..."
    yaml_sed_set "$CLUSTER_YAML" "domain" "\"$CDOMAIN\""
    yaml_sed_set "$CLUSTER_YAML" "issuer_url" "\"https://auth.${CDOMAIN}/realms/broker\""
    yaml_sed_set "$CLUSTER_YAML" "root_idp_url" "\"https://idp.${SUPPORT_DOMAIN}\""
done

# ============================================================================
# 4. Generate OpenTofu terraform.tfvars
# ============================================================================
echo "  Generating tofu/environments/*/terraform.tfvars..."

# base/terraform.tfvars
cat > "$PROJECT_ROOT/tofu/environments/base/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr       = "${VAULT_URL}"
keycloak_url     = "${KEYCLOAK_URL}"
minio_endpoint   = "minio.${SUPPORT_DOMAIN}"
gitlab_url       = "${GITLAB_URL}"
ziti_api_url     = "https://${ZITI_DOMAIN}:2029/edge/management/v1"
teleport_addr    = "${TELEPORT_ADDR}"
harbor_url       = "${HARBOR_URL}"
base_domain      = "${BASE_DOMAIN}"
support_domain   = "${SUPPORT_DOMAIN}"
email_domain     = "${BASE_DOMAIN}"
cluster_names    = ["$(echo $(get_clusters) | sed 's/ /", "/g')"]
EOF

# Per-cluster tfvars
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    cat > "$PROJECT_ROOT/tofu/environments/$CLUSTER/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr          = "${VAULT_URL}"
harbor_url          = "${HARBOR_URL}"
broker_keycloak_url = "https://auth.${CDOMAIN}"
base_domain         = "${BASE_DOMAIN}"
support_domain      = "${SUPPORT_DOMAIN}"
EOF
done

# ============================================================================
# 5. Generate OpenTofu backend.tf
# ============================================================================
echo "  Generating tofu/environments/*/backend.tf..."

generate_backend() {
    local env="$1" key="$2"
    cat > "$PROJECT_ROOT/tofu/environments/$env/backend.tf" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
terraform {
  backend "s3" {
    bucket = "tofu-state"
    key    = "${key}/terraform.tfstate"
    region = "us-east-1"

    # MinIO S3-compatible backend
    endpoints = {
      s3 = "${MINIO_URL}"
    }

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_path_style              = true
  }
}
EOF
}

generate_backend "base" "base"
for CLUSTER in $(get_clusters); do
    generate_backend "$CLUSTER" "$CLUSTER"
done

# ============================================================================
# 6. Generate .push-guard (patterns for pre-push hook)
# ============================================================================
echo "  Generating .push-guard..."
cat > "$PROJECT_ROOT/.push-guard" << EOF
# Personal domain patterns — blocked from GitHub pushes
# Used by .githooks/pre-push
${SUPPORT_DOMAIN}
${BASE_DOMAIN}
${ROOT_DOMAIN}
${ZITI_DOMAIN}
${ADMIN_EMAIL}
EOF

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "Config generated successfully."
echo ""
echo "Generated files (gitignored on main):"
echo "  stages/lib/config-local.sh"
echo "  iac/provision/nix/supporting-systems/generated-config.nix"
echo "  tofu/environments/*/terraform.tfvars"
echo "  tofu/environments/*/backend.tf"
echo "  .push-guard"
echo ""
echo "Updated tracked files:"
echo "  iac/clusters/*/cluster.yaml"
echo ""
echo "Next: run 'just generate' to generate per-cluster configs."
