#!/usr/bin/env bash
# Generate local configuration from config.yaml
#
# Reads config.yaml and produces/updates ALL files with deployment-specific
# domains, hostnames, and URLs. Covers:
#   - stages/lib/config-local.sh                  (shell variables)
#   - iac/provision/nix/supporting-systems/        (NixOS config + acme.nix)
#   - iac/argocd/base/*.yaml                       (ArgoCD Application repoURLs)
#   - iac/argocd/clusters/*/*.yaml                 (per-cluster ArgoCD apps)
#   - iac/argocd/clusters/*/kustomize/**/*.yaml    (per-cluster kustomize overlays)
#   - iac/argocd/values/{base,kss,kcs}/*.yaml      (Helm values)
#   - iac/kustomize/base/*/                        (kustomize bases)
#   - iac/clusters/*/cluster.yaml                  (cluster domain + OIDC URLs)
#   - tofu/environments/*/                         (tfvars, backend, providers, variables)
#   - tofu/modules/*/                              (vault, keycloak, gitlab, teleport)
#
# Usage: ./scripts/generate-config.sh [--check]
#   --check: verify config.yaml exists without generating

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/config.yaml"

# ─── Preflight ───────────────────────────────────────────────────────────────

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE not found."
    echo "Copy config.yaml.example to config.yaml and fill in your values:"
    echo "  cp config.yaml.example config.yaml"
    exit 1
fi

if ! command -v yq &>/dev/null; then
    echo "ERROR: yq is required but not found. Run: nix develop"
    exit 1
fi

if [ "${1:-}" = "--check" ]; then
    echo "config.yaml found and valid."
    exit 0
fi

# ─── Read config.yaml ────────────────────────────────────────────────────────

cfg() { yq -r "$1" "$CONFIG_FILE"; }

# yq in-place edit helper (Python yq doesn't support -i)
# Uses yq -y which reformats YAML — only use for files where formatting loss is acceptable
yq_set() {
    local file="$1"
    local path="$2"
    local value="$3"
    local tmp
    tmp=$(mktemp)
    yq -y "${path} = \"${value}\"" "$file" > "$tmp" && mv "$tmp" "$file"
}

# sed-based YAML value replacement — preserves comments and formatting
# Usage: yaml_sed_set file.yaml "key" "new_value"
# Replaces the value on lines matching "key: old_value" with "key: new_value"
yaml_sed_set() {
    local file="$1"
    local key="$2"
    local value="$3"
    sed -i "s|^\(\s*${key}:\s*\).*|\1${value}|" "$file"
}

ROOT_DOMAIN=$(cfg '.domains.root')
BASE_DOMAIN=$(cfg '.domains.base')
SUPPORT_PREFIX=$(cfg '.domains.support_prefix')
ZITI_DOMAIN=$(cfg '.domains.ziti')

HYPERVISOR=$(cfg '.hosts.hypervisor')
REMOTE_PROJECT_DIR=$(cfg '.hosts.remote_project_dir')

SUPPORT_IP=$(cfg '.support.ip')
TELEPORT_CLUSTER_NAME=$(cfg '.support.teleport_cluster_name')

ADMIN_EMAIL=$(cfg '.identity.admin_email')

NFS_ALLOWED_NETWORK=$(cfg '.network.nfs_allowed_network')
OLLAMA_URL=$(cfg '.network.ollama_url')

GIT_PROJECT_NAME=$(cfg '.git.project_name')
GITHUB_ORG=$(cfg '.git.github_org')

# ─── Derived values ──────────────────────────────────────────────────────────

SUPPORT_DOMAIN="${SUPPORT_PREFIX}.${BASE_DOMAIN}"
VAULT_URL="https://vault.${SUPPORT_DOMAIN}"
HARBOR_URL="https://harbor.${SUPPORT_DOMAIN}"
MINIO_URL="https://minio.${SUPPORT_DOMAIN}"
GITLAB_URL="https://gitlab.${SUPPORT_DOMAIN}"
KEYCLOAK_URL="https://idp.${SUPPORT_DOMAIN}"
TELEPORT_ADDR="teleport.${SUPPORT_DOMAIN}:3080"
LETSENCRYPT_EMAIL="letsencrypt@${ROOT_DOMAIN}"
PORTAL_PREFIX="portal.${BASE_DOMAIN}"

# Git
GITLAB_SSH_HOST="[gitlab.${SUPPORT_DOMAIN}]:2222"
GIT_REPO_URL="ssh://git@gitlab.${SUPPORT_DOMAIN}:2222/infra/${GIT_PROJECT_NAME}.git"

echo "Generating config from $CONFIG_FILE..."
echo "  Root domain:    $ROOT_DOMAIN"
echo "  Base domain:    $BASE_DOMAIN"
echo "  Support domain: $SUPPORT_DOMAIN"
echo "  Ziti domain:    $ZITI_DOMAIN"

# ─── Helper: get cluster names ───────────────────────────────────────────────

get_clusters() {
    local clusters=()
    for dir in "$PROJECT_ROOT"/iac/clusters/*/; do
        if [ -f "${dir}cluster.yaml" ]; then
            clusters+=("$(basename "$dir")")
        fi
    done
    echo "${clusters[@]}"
}

cluster_domain() {
    local name="$1"
    echo "${name}.${BASE_DOMAIN}"
}

domain_slug() {
    echo "$1" | tr '.' '-'
}

# ============================================================================
# 1. Generate stages/lib/config-local.sh
# ============================================================================
echo "  Generating stages/lib/config-local.sh..."
cat > "$PROJECT_ROOT/stages/lib/config-local.sh" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml

REMOTE_HOST="$HYPERVISOR"
REMOTE_PROJECT_DIR="\$HOME/$(echo "$REMOTE_PROJECT_DIR" | sed 's|^~/||')"
SUPPORT_VM_IP="$SUPPORT_IP"
VAULT_URL="$VAULT_URL"
EOF

# ============================================================================
# 2. Generate NixOS config
# ============================================================================
echo "  Generating iac/provision/nix/supporting-systems/generated-config.nix..."
cat > "$PROJECT_ROOT/iac/provision/nix/supporting-systems/generated-config.nix" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml
{
  domain = "${SUPPORT_DOMAIN}";
  rootDomain = "${ROOT_DOMAIN}";
  baseDomain = "${BASE_DOMAIN}";
  supportPrefix = "${SUPPORT_PREFIX}";
  zitiDomain = "${ZITI_DOMAIN}";
  adminEmail = "${ADMIN_EMAIL}";
  supportIp = "${SUPPORT_IP}";
  teleportClusterName = "${TELEPORT_CLUSTER_NAME}";
  githubOrg = "${GITHUB_ORG}";
  gitlabSshHost = "${GITLAB_SSH_HOST}";
  nfsAllowedNetwork = "${NFS_ALLOWED_NETWORK}";
}
EOF

# ============================================================================
# 3. Update cluster.yaml files
# ============================================================================
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    CLUSTER_YAML="$PROJECT_ROOT/iac/clusters/$CLUSTER/cluster.yaml"

    echo "  Updating $CLUSTER/cluster.yaml..."
    yaml_sed_set "$CLUSTER_YAML" "domain" "\"$CDOMAIN\""
    yaml_sed_set "$CLUSTER_YAML" "issuer_url" "\"https://auth.${CDOMAIN}/realms/broker\""
    yaml_sed_set "$CLUSTER_YAML" "root_idp_url" "\"https://idp.${SUPPORT_DOMAIN}\""
done

# ============================================================================
# 4. Generate per-cluster Helm values
# ============================================================================
generate_cluster_values() {
    local CLUSTER="$1"
    local CDOMAIN
    CDOMAIN=$(cluster_domain "$CLUSTER")
    local DSLUG
    DSLUG=$(domain_slug "$CDOMAIN")
    local VALUES_DIR="$PROJECT_ROOT/iac/argocd/values/$CLUSTER"
    local CLUSTER_YAML="$PROJECT_ROOT/iac/clusters/$CLUSTER/cluster.yaml"
    local HELMFILE_ENV
    HELMFILE_ENV=$(yq -r '.helmfile_env // "default"' "$CLUSTER_YAML")

    echo "  Generating Helm values for $CLUSTER ($CDOMAIN)..."

    # --- argocd.yaml ---
    {
        echo "# ArgoCD — $CLUSTER cluster overrides"
        echo "server:"
        echo "  ingress:"
        echo "    hostname: argocd.${CDOMAIN}"
        if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
            echo "    enabled: false  # Uses Gateway API HTTPRoute"
        fi
        echo ""
        echo "configs:"
        echo "  cm:"
        echo "    url: \"https://argocd.${CDOMAIN}\""
        echo "    oidc.config: |"
        echo "      name: Keycloak"
        echo "      issuer: https://auth.${CDOMAIN}/realms/broker"
        echo "      clientID: argocd"
        echo "      clientSecret: \$argocd-oidc-secret:client-secret"
        echo "      requestedScopes:"
        echo "        - openid"
        echo "        - profile"
        echo "        - email"
        echo "        - groups"
    } > "$VALUES_DIR/argocd.yaml"

    # --- monitoring.yaml ---
    {
        echo "# kube-prometheus-stack — $CLUSTER cluster overrides"
        echo "grafana:"
        echo "  ingress:"
        if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
            echo "    enabled: false  # Uses Gateway API HTTPRoute"
        fi
        cat << YAMLEOF
    hosts:
      - grafana.${CDOMAIN}
    tls:
      - secretName: wildcard-${DSLUG}-tls
        hosts:
          - grafana.${CDOMAIN}
  grafana.ini:
    server:
      root_url: "https://grafana.${CDOMAIN}"
    auth.generic_oauth:
      auth_url: "https://auth.${CDOMAIN}/realms/broker/protocol/openid-connect/auth"
      token_url: "https://auth.${CDOMAIN}/realms/broker/protocol/openid-connect/token"
      api_url: "https://auth.${CDOMAIN}/realms/broker/protocol/openid-connect/userinfo"
YAMLEOF
    } > "$VALUES_DIR/monitoring.yaml"

    # --- oauth2-proxy.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/oauth2-proxy.yaml" << YAMLEOF
# OAuth2-Proxy — $CLUSTER cluster overrides
# redirect-url is the centralized OIDC callback. After Keycloak auth, the
# browser returns here. OAuth2-Proxy then redirects to the original app URL
# (stored in the state parameter via X-Auth-Request-Redirect header injected
# by the envoyfilter-auth-redirect Lua filter on the gateway).
extraArgs:
  oidc-issuer-url: "https://auth.${CDOMAIN}/realms/broker"
  cookie-domain: ".${CDOMAIN}"
  whitelist-domain: ".${CDOMAIN}"
  redirect-url: "https://oauth2-proxy.${CDOMAIN}/oauth2/callback"

ingress:
  enabled: false  # Uses Gateway API HTTPRoute
  hosts:
    - oauth2-proxy.${CDOMAIN}
  tls:
    - secretName: oauth2-proxy-tls
      hosts:
        - oauth2-proxy.${CDOMAIN}
YAMLEOF
    else
        cat > "$VALUES_DIR/oauth2-proxy.yaml" << YAMLEOF
# OAuth2-Proxy — $CLUSTER cluster overrides
extraArgs:
  oidc-issuer-url: "https://auth.${CDOMAIN}/realms/broker"
  cookie-domain: ".${CDOMAIN}"
  whitelist-domain: ".${CDOMAIN}"
  redirect-url: "https://oauth2-proxy.${CDOMAIN}/oauth2/callback"

ingress:
  hosts:
    - oauth2-proxy.${CDOMAIN}
  tls:
    - secretName: oauth2-proxy-tls
      hosts:
        - oauth2-proxy.${CDOMAIN}
YAMLEOF
    fi

    # --- open-webui.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/open-webui.yaml" << YAMLEOF
ingress:
  enabled: false  # Uses Istio Gateway API HTTPRoute

sso:
  oidc:
    providerUrl: "https://auth.${CDOMAIN}/realms/broker/.well-known/openid-configuration"
YAMLEOF
    else
        cat > "$VALUES_DIR/open-webui.yaml" << YAMLEOF
ingress:
  enabled: true
  class: nginx
  annotations:
    ${PORTAL_PREFIX}/name: "Open WebUI"
    ${PORTAL_PREFIX}/icon: "chat"
  host: chat.${CDOMAIN}
  tls: true
  existingSecret: wildcard-${DSLUG}-tls

sso:
  oidc:
    providerUrl: "https://auth.${CDOMAIN}/realms/broker/.well-known/openid-configuration"
YAMLEOF
    fi

    # --- spire.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/spire.yaml" << YAMLEOF
# SPIRE — $CLUSTER cluster overrides
global:
  spire:
    trustDomain: ${CDOMAIN}
    clusterName: ${CLUSTER}

spire-server:
  oidcDiscoveryProvider:
    ingress:
      enabled: false
YAMLEOF
    else
        cat > "$VALUES_DIR/spire.yaml" << YAMLEOF
# SPIRE — $CLUSTER cluster overrides
global:
  spire:
    trustDomain: ${CDOMAIN}
    clusterName: ${CLUSTER}

spire-server:
  oidcDiscoveryProvider:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - spire-oidc.${CDOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: spire-oidc-tls
          hosts:
            - spire-oidc.${CDOMAIN}
YAMLEOF
    fi

    # --- headlamp.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/headlamp.yaml" << YAMLEOF
# Headlamp — $CLUSTER cluster overrides (no ingress, uses HTTPRoute)
ingress:
  enabled: false
YAMLEOF
    else
        cat > "$VALUES_DIR/headlamp.yaml" << YAMLEOF
# Headlamp — $CLUSTER cluster overrides
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    ${PORTAL_PREFIX}/name: "Headlamp"
    ${PORTAL_PREFIX}/description: "Kubernetes dashboard"
    ${PORTAL_PREFIX}/icon: "\U0001F4BB"
    ${PORTAL_PREFIX}/category: "Platform"
    ${PORTAL_PREFIX}/order: "20"
  hosts:
    - host: headlamp.${CDOMAIN}
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: wildcard-${DSLUG}-tls
      hosts:
        - headlamp.${CDOMAIN}
YAMLEOF
    fi

    # --- longhorn.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/longhorn.yaml" << YAMLEOF
# Longhorn — $CLUSTER cluster overrides
ingress:
  enabled: false  # Uses Gateway API HTTPRoute
  host: longhorn.${CDOMAIN}
  tls: true
  tlsSecret: wildcard-${DSLUG}-tls
YAMLEOF
    else
        cat > "$VALUES_DIR/longhorn.yaml" << YAMLEOF
# Longhorn — $CLUSTER cluster overrides
ingress:
  host: longhorn.${CDOMAIN}
  tls: true
  tlsSecret: wildcard-${DSLUG}-tls
YAMLEOF
    fi

    # --- ziti-router.yaml ---
    cat > "$VALUES_DIR/ziti-router.yaml" << YAMLEOF
# $CLUSTER cluster ziti-router overrides

# Advertised address for this cluster's router
edge:
  advertisedHost: ziti-router.${CDOMAIN}
  advertisedPort: 443
YAMLEOF

    # --- loki.yaml ---
    cat > "$VALUES_DIR/loki.yaml" << YAMLEOF
# Loki — $CLUSTER cluster overrides
loki:
  storage:
    s3:
      bucketnames: loki-${CLUSTER}
    bucketNames:
      chunks: loki-${CLUSTER}
      ruler: loki-${CLUSTER}
      admin: loki-${CLUSTER}
YAMLEOF

    # --- teleport-kube-agent.yaml ---
    cat > "$VALUES_DIR/teleport-kube-agent.yaml" << YAMLEOF
# $CLUSTER cluster teleport-kube-agent overrides

kubeClusterName: "${CLUSTER}"

labels:
  env: homelab
  cluster: ${CLUSTER}

apps:
  - name: "grafana-${CLUSTER}"
    uri: "http://grafana.monitoring.svc.cluster.local:3000"
    labels:
      env: homelab
      cluster: ${CLUSTER}
  - name: "argocd-${CLUSTER}"
    uri: "https://argocd-server.argocd.svc.cluster.local:443"
    insecure_skip_verify: true
    labels:
      env: homelab
      cluster: ${CLUSTER}
  - name: "headlamp-${CLUSTER}"
    uri: "http://headlamp.headlamp.svc.cluster.local:80"
    labels:
      env: homelab
      cluster: ${CLUSTER}
YAMLEOF

    # --- external-dns.yaml ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/external-dns.yaml" << YAMLEOF
# ExternalDNS — $CLUSTER cluster overrides
txtOwnerId: "k8s-cluster-${CLUSTER}"

sources:
  - service
  - ingress
  - gateway-httproute
YAMLEOF
    else
        cat > "$VALUES_DIR/external-dns.yaml" << YAMLEOF
# ExternalDNS — $CLUSTER cluster overrides
txtOwnerId: "k8s-cluster-${CLUSTER}"
YAMLEOF
    fi

    # --- kiali.yaml (kcs only) ---
    if [ "$HELMFILE_ENV" = "istio-mesh" ]; then
        cat > "$VALUES_DIR/kiali.yaml" << YAMLEOF
# Kiali — $CLUSTER cluster values
auth:
  strategy: openid
  openid:
    client_id: kiali
    issuer_uri: "https://auth.${CDOMAIN}/realms/broker"
    scopes:
      - openid
      - profile
      - email
      - groups
    username_claim: preferred_username
    disable_rbac: true

external_services:
  prometheus:
    url: "http://kube-prometheus-stack-prometheus.monitoring:9090"
  grafana:
    enabled: true
    in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring:80"
    url: "https://grafana.${CDOMAIN}"
  tracing:
    enabled: false

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi

server:
  port: 20001
  web_fqdn: kiali.${CDOMAIN}
  web_port: "443"
  web_root: /
  web_schema: https
YAMLEOF
    fi

    # --- Preserve non-generated files ---
    # cilium.yaml, istio-istiod.yaml are cluster-specific but domain-independent
    # They are not generated — keep existing versions
}

for CLUSTER in $(get_clusters); do
    generate_cluster_values "$CLUSTER"
done

# ============================================================================
# 5. Update base Helm values (targeted replacements)
# ============================================================================
echo "  Updating base Helm values..."

BASE_VALUES="$PROJECT_ROOT/iac/argocd/values/base"

# argocd-image-updater.yaml — Harbor URL
sed -i "s|api_url: https://harbor\.[a-zA-Z0-9._-]*|api_url: ${HARBOR_URL}|" "$BASE_VALUES/argocd-image-updater.yaml"
sed -i "s|prefix: harbor\.[a-zA-Z0-9._-]*|prefix: harbor.${SUPPORT_DOMAIN}|" "$BASE_VALUES/argocd-image-updater.yaml"

# argocd.yaml — GitLab SSH host and portal annotations
sed -i "s|portal\.[a-zA-Z0-9._-]*/name|${PORTAL_PREFIX}/name|g" "$BASE_VALUES/argocd.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/description|${PORTAL_PREFIX}/description|g" "$BASE_VALUES/argocd.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/icon|${PORTAL_PREFIX}/icon|g" "$BASE_VALUES/argocd.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/category|${PORTAL_PREFIX}/category|g" "$BASE_VALUES/argocd.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/order|${PORTAL_PREFIX}/order|g" "$BASE_VALUES/argocd.yaml"
# GitLab SSH host in comment
sed -i "s|ssh-keyscan -p 2222 [a-zA-Z0-9._-]*|ssh-keyscan -p 2222 gitlab.${SUPPORT_DOMAIN}|" "$BASE_VALUES/argocd.yaml"
# GitLab SSH host keys — replace hostname prefix only
sed -i "s|\[gitlab\.[a-zA-Z0-9._-]*\]:2222|${GITLAB_SSH_HOST}|g" "$BASE_VALUES/argocd.yaml"

# external-dns.yaml — root domain filter (only under domainFilters:)
sed -i "/^domainFilters:/{ n; s|  - [a-zA-Z0-9._-]*|  - ${ROOT_DOMAIN}| }" "$BASE_VALUES/external-dns.yaml"

# loki.yaml — MinIO endpoint
sed -i "s|endpoint: https://minio\.[a-zA-Z0-9._-]*|endpoint: ${MINIO_URL}|" "$BASE_VALUES/loki.yaml"

# longhorn.yaml — NFS backup target and portal annotations
sed -i "s|backupTarget: \"nfs://[0-9.]*:/export/longhorn\"|backupTarget: \"nfs://${SUPPORT_IP}:/export/longhorn\"|" "$BASE_VALUES/longhorn.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/name|${PORTAL_PREFIX}/name|g" "$BASE_VALUES/longhorn.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/description|${PORTAL_PREFIX}/description|g" "$BASE_VALUES/longhorn.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/icon|${PORTAL_PREFIX}/icon|g" "$BASE_VALUES/longhorn.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/category|${PORTAL_PREFIX}/category|g" "$BASE_VALUES/longhorn.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/order|${PORTAL_PREFIX}/order|g" "$BASE_VALUES/longhorn.yaml"

# monitoring.yaml — portal annotations
sed -i "s|portal\.[a-zA-Z0-9._-]*/name|${PORTAL_PREFIX}/name|g" "$BASE_VALUES/monitoring.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/description|${PORTAL_PREFIX}/description|g" "$BASE_VALUES/monitoring.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/icon|${PORTAL_PREFIX}/icon|g" "$BASE_VALUES/monitoring.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/category|${PORTAL_PREFIX}/category|g" "$BASE_VALUES/monitoring.yaml"
sed -i "s|portal\.[a-zA-Z0-9._-]*/order|${PORTAL_PREFIX}/order|g" "$BASE_VALUES/monitoring.yaml"

# oauth2-proxy.yaml — portal annotations (base has no domains, only per-cluster)
# No domain changes needed in base oauth2-proxy.yaml

# teleport-kube-agent.yaml — Teleport proxy address
sed -i "s|proxyAddr: \"teleport\.[a-zA-Z0-9._-]*:3080\"|proxyAddr: \"${TELEPORT_ADDR}\"|" "$BASE_VALUES/teleport-kube-agent.yaml"

# ziti-router.yaml — Ziti controller endpoint
sed -i "s|endpoint: \"[a-zA-Z0-9._-]*:2029\"|endpoint: \"${ZITI_DOMAIN}:2029\"|" "$BASE_VALUES/ziti-router.yaml"

# open-webui.yaml — Ollama URL
sed -i "s|\"http://[0-9.]*:11434\"|\"${OLLAMA_URL}\"|" "$BASE_VALUES/open-webui.yaml"

# headlamp.yaml (base) — portal annotations if present
if [ -f "$BASE_VALUES/headlamp.yaml" ]; then
    sed -i "s|portal\.[a-zA-Z0-9._-]*/name|${PORTAL_PREFIX}/name|g" "$BASE_VALUES/headlamp.yaml" 2>/dev/null || true
    sed -i "s|portal\.[a-zA-Z0-9._-]*/description|${PORTAL_PREFIX}/description|g" "$BASE_VALUES/headlamp.yaml" 2>/dev/null || true
    sed -i "s|portal\.[a-zA-Z0-9._-]*/icon|${PORTAL_PREFIX}/icon|g" "$BASE_VALUES/headlamp.yaml" 2>/dev/null || true
    sed -i "s|portal\.[a-zA-Z0-9._-]*/category|${PORTAL_PREFIX}/category|g" "$BASE_VALUES/headlamp.yaml" 2>/dev/null || true
    sed -i "s|portal\.[a-zA-Z0-9._-]*/order|${PORTAL_PREFIX}/order|g" "$BASE_VALUES/headlamp.yaml" 2>/dev/null || true
fi

# ============================================================================
# 6. Update kustomize base files
# ============================================================================
echo "  Updating kustomize bases..."

KUSTOMIZE_BASE="$PROJECT_ROOT/iac/kustomize/base"

# cert-manager/cluster-issuer.yaml — email, DNS zone, and comments
sed -i "s|email: [a-zA-Z0-9._@-]*|email: ${LETSENCRYPT_EMAIL}|g" "$KUSTOMIZE_BASE/cert-manager/cluster-issuer.yaml"
# Replace the domain under dnsZones (line after "- ")
sed -i "/dnsZones:/{ n; s|            - .*|            - ${ROOT_DOMAIN}| }" "$KUSTOMIZE_BASE/cert-manager/cluster-issuer.yaml"
# Comments referencing domain
sed -i "s|domain in [a-zA-Z0-9._-]*$|domain in ${ROOT_DOMAIN}|g" "$KUSTOMIZE_BASE/cert-manager/cluster-issuer.yaml"
sed -i "s|solver for [a-zA-Z0-9._-]* domain|solver for ${ROOT_DOMAIN} domain|g" "$KUSTOMIZE_BASE/cert-manager/cluster-issuer.yaml"

# cert-manager/wildcard-certificate.yaml — comments referencing domain
sed -i "s|subdomains under [a-zA-Z0-9._-]*$|subdomains under ${SUPPORT_DOMAIN}|g" "$KUSTOMIZE_BASE/cert-manager/wildcard-certificate.yaml" 2>/dev/null || true

# external-secrets/cluster-secret-store.yaml — Vault URL
sed -i "s|server: \"https://vault\.[a-zA-Z0-9._-]*\"|server: \"${VAULT_URL}\"|" "$KUSTOMIZE_BASE/external-secrets/cluster-secret-store.yaml"

# harbor/harbor-pull-secret.yaml — Harbor URL (appears many times)
sed -i "s|harbor\.[a-zA-Z0-9._-]*\"|harbor.${SUPPORT_DOMAIN}\"|g" "$KUSTOMIZE_BASE/harbor/harbor-pull-secret.yaml"

# apps-discovery/ — GitLab and Harbor URLs
if [ -d "$KUSTOMIZE_BASE/apps-discovery" ]; then
    # argocd-repo-creds-apps.yaml
    sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222|ssh://git@gitlab.${SUPPORT_DOMAIN}:2222|g" \
        "$KUSTOMIZE_BASE/apps-discovery/argocd-repo-creds-apps.yaml"

    # harbor-image-updater-secret.yaml
    sed -i "s|harbor\.[a-zA-Z0-9._-]*\"|harbor.${SUPPORT_DOMAIN}\"|g" \
        "$KUSTOMIZE_BASE/apps-discovery/harbor-image-updater-secret.yaml"

    # harbor-pull-secret-apps.yaml
    sed -i "s|harbor\.[a-zA-Z0-9._-]*\"|harbor.${SUPPORT_DOMAIN}\"|g" \
        "$KUSTOMIZE_BASE/apps-discovery/harbor-pull-secret-apps.yaml"
fi

# Update portal annotations in kustomize base files
for f in $(grep -rl "portal\." "$KUSTOMIZE_BASE" --include='*.yaml' 2>/dev/null || true); do
    sed -i "s|portal\.[a-zA-Z0-9._-]*/name|${PORTAL_PREFIX}/name|g" "$f"
    sed -i "s|portal\.[a-zA-Z0-9._-]*/description|${PORTAL_PREFIX}/description|g" "$f"
    sed -i "s|portal\.[a-zA-Z0-9._-]*/icon|${PORTAL_PREFIX}/icon|g" "$f"
    sed -i "s|portal\.[a-zA-Z0-9._-]*/category|${PORTAL_PREFIX}/category|g" "$f"
    sed -i "s|portal\.[a-zA-Z0-9._-]*/order|${PORTAL_PREFIX}/order|g" "$f"
done

# Portal configmap — annotation prefix
sed -i "s|portal\.[a-zA-Z0-9._-]*/\"|${PORTAL_PREFIX}/\"|" \
    "$KUSTOMIZE_BASE/portal/configmap.yaml" 2>/dev/null || true

# Kustomize base files with cluster-specific domains (kss as default, overridden per-cluster)
BASE_KUSTOMIZE_CLUSTER_FILES=(
    "$KUSTOMIZE_BASE/keycloak/keycloak-ingress.yaml"
    "$KUSTOMIZE_BASE/keycloak/keycloak-instance.yaml"
    "$KUSTOMIZE_BASE/cluster-setup/ingress.yaml"
    "$KUSTOMIZE_BASE/cluster-setup/configmap.yaml"
    "$KUSTOMIZE_BASE/jit-elevation/ingress.yaml"
    "$KUSTOMIZE_BASE/jit-elevation/configmap.yaml"
)
for f in "${BASE_KUSTOMIZE_CLUSTER_FILES[@]}"; do
    [ -f "$f" ] || continue
    for CLUSTER in $(get_clusters); do
        CDOMAIN=$(cluster_domain "$CLUSTER")
        sed -i "s|\([a-zA-Z0-9_-]*\)\.${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\1.${CDOMAIN}|g" "$f"
        sed -i "s|\"${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|\"${CDOMAIN}\"|g" "$f"
    done
done

# Update Harbor image references in kustomize deployment files
for f in $(grep -rl "harbor\." "$KUSTOMIZE_BASE" --include='*.yaml' 2>/dev/null | grep -v pull-secret || true); do
    sed -i "s|harbor\.[a-zA-Z0-9._-]*/|harbor.${SUPPORT_DOMAIN}/|g" "$f"
done

# Update GitLab API URL in kustomize
sed -i "s|https://gitlab\.[a-zA-Z0-9._-]*/|${GITLAB_URL}/|g" \
    "$KUSTOMIZE_BASE/mcpo/deployment.yaml" 2>/dev/null || true

# ============================================================================
# 7. Generate OpenTofu tfvars
# ============================================================================
echo "  Generating OpenTofu tfvars..."

# base/terraform.tfvars
cat > "$PROJECT_ROOT/tofu/environments/base/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr  = "${VAULT_URL}"
keycloak_url = "${KEYCLOAK_URL}"
minio_endpoint = "minio.${SUPPORT_DOMAIN}"
gitlab_url = "${GITLAB_URL}"
ziti_api_url = "https://${ZITI_DOMAIN}:2029/edge/management/v1"
teleport_addr = "${TELEPORT_ADDR}"
harbor_url = "${HARBOR_URL}"
EOF

# Per-cluster tfvars
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    cat > "$PROJECT_ROOT/tofu/environments/$CLUSTER/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr  = "${VAULT_URL}"
harbor_url = "${HARBOR_URL}"
EOF
done

# ============================================================================
# 8. Update OpenTofu tracked files
# ============================================================================
echo "  Updating OpenTofu files..."

TOFU_MODULES="$PROJECT_ROOT/tofu/modules"

# --- 8a. Environment files ---

# base/variables.tf — update defaults
sed -i "s|default     = \"https://vault\.[a-zA-Z0-9._-]*\"|default     = \"${VAULT_URL}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"https://idp\.[a-zA-Z0-9._-]*\"|default     = \"${KEYCLOAK_URL}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"minio\.[a-zA-Z0-9._-]*\"|default     = \"minio.${SUPPORT_DOMAIN}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"https://gitlab\.[a-zA-Z0-9._-]*\"|default     = \"${GITLAB_URL}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"https://z\.[a-zA-Z0-9._-]*:2029/edge/management/v1\"|default     = \"https://${ZITI_DOMAIN}:2029/edge/management/v1\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"teleport\.[a-zA-Z0-9._-]*:3080\"|default     = \"${TELEPORT_ADDR}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"
sed -i "s|default     = \"https://harbor\.[a-zA-Z0-9._-]*\"|default     = \"${HARBOR_URL}\"|g" \
    "$PROJECT_ROOT/tofu/environments/base/variables.tf"

# base/backend.tf — MinIO endpoint
sed -i "s|s3 = \"https://minio\.[a-zA-Z0-9._-]*\"|s3 = \"${MINIO_URL}\"|" \
    "$PROJECT_ROOT/tofu/environments/base/backend.tf"

# Per-cluster environment files
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    CLUSTER_DIR="$PROJECT_ROOT/tofu/environments/$CLUSTER"

    # backend.tf — MinIO endpoint
    sed -i "s|s3 = \"https://minio\.[a-zA-Z0-9._-]*\"|s3 = \"${MINIO_URL}\"|" "$CLUSTER_DIR/backend.tf"

    # providers.tf — Keycloak broker URL
    sed -i "s|url       = \"https://auth\.[a-zA-Z0-9._-]*\"|url       = \"https://auth.${CDOMAIN}\"|" "$CLUSTER_DIR/providers.tf"

    # Per-cluster variables.tf — update defaults
    if [ -f "$CLUSTER_DIR/variables.tf" ]; then
        sed -i "s|default     = \"https://vault\.[a-zA-Z0-9._-]*\"|default     = \"${VAULT_URL}\"|g" "$CLUSTER_DIR/variables.tf"
        sed -i "s|default     = \"https://harbor\.[a-zA-Z0-9._-]*\"|default     = \"${HARBOR_URL}\"|g" "$CLUSTER_DIR/variables.tf"
    fi

    # Per-cluster main.tf — domain in keycloak_broker module
    if [ -f "$CLUSTER_DIR/main.tf" ]; then
        sed -i "s|domain       = \"[a-zA-Z0-9._-]*\"|domain       = \"${CDOMAIN}\"|" "$CLUSTER_DIR/main.tf"
    fi
done

# --- 8b. base/main.tf — support + cluster domain references in Ziti overlay ---
BASE_MAIN="$PROJECT_ROOT/tofu/environments/base/main.tf"
for svc in vault harbor minio minio-console gitlab zac keycloak idp teleport; do
    sed -i "s|${svc}\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${svc}.${SUPPORT_DOMAIN}|g" \
        "$BASE_MAIN"
done
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    # Match cluster service domains: argocd.kss.old.domain → argocd.kss.new_base
    sed -i "s|\([a-zA-Z0-9_*-]*\)\.${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\1.${CDOMAIN}|g" \
        "$BASE_MAIN"
done

# --- 8c. vault-base — PKI URLs ---
sed -i "s|vault\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*/|vault.${SUPPORT_DOMAIN}/|g" \
    "$TOFU_MODULES/vault-base/main.tf"

# --- 8d. vault-cluster — PKI role name + allowed_domains + policies ---
sed -i "/vault_pki_secret_backend_role/,/^}/ s|name    = \"[a-zA-Z0-9_-]*\"|name    = \"${SUPPORT_PREFIX}\"|" \
    "$TOFU_MODULES/vault-cluster/main.tf"
sed -i "s|allowed_domains    = \[\"[^\"]*\", \"[^\"]*\"\]|allowed_domains    = [\"${SUPPORT_DOMAIN}\", \"${BASE_DOMAIN}\"]|" \
    "$TOFU_MODULES/vault-cluster/main.tf"
sed -i "s|pki_int/issue/[a-zA-Z0-9_-]*\"|pki_int/issue/${SUPPORT_PREFIX}\"|" \
    "$TOFU_MODULES/vault-cluster/policies.tf"

# --- 8e. keycloak-broker — upstream issuer default ---
sed -i "s|https://idp\.[a-zA-Z0-9._-]*/realms/upstream|${KEYCLOAK_URL}/realms/upstream|g" \
    "$TOFU_MODULES/keycloak-broker/variables.tf"

# --- 8f. keycloak-upstream — user emails, callback URLs ---
# Email addresses (exclude SSH URLs by skipping lines with ssh://)
sed -i "/ssh:\/\//!s|@[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|@${BASE_DOMAIN}\"|g" \
    "$TOFU_MODULES/keycloak-upstream/main.tf"
# Teleport callback URL
sed -i "s|teleport\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*:3080|teleport.${SUPPORT_DOMAIN}:3080|g" \
    "$TOFU_MODULES/keycloak-upstream/main.tf"
# GitLab callback URL
sed -i "s|gitlab\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*/|gitlab.${SUPPORT_DOMAIN}/|g" \
    "$TOFU_MODULES/keycloak-upstream/main.tf"
# Broker client redirect URIs — rewrite the valid_redirect_uris block
BROKER_URIS=""
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    BROKER_URIS="${BROKER_URIS}    \"https://auth.${CDOMAIN}/realms/broker/broker/upstream/endpoint\",\n"
done
tmp=$(mktemp)
awk -v uris="$BROKER_URIS" '
    /resource "keycloak_openid_client" "broker_client"/ { in_broker=1 }
    in_broker && /valid_redirect_uris = \[/ {
        print "  valid_redirect_uris = ["
        printf "%s", uris
        print "  ]"
        while (getline > 0 && $0 !~ /^\s*\]/) {}
        in_broker=0
        next
    }
    { print }
' "$TOFU_MODULES/keycloak-upstream/main.tf" > "$tmp" && mv "$tmp" "$TOFU_MODULES/keycloak-upstream/main.tf"

# --- 8g. gitlab-config — email, SSH host, repo URL ---
# SSH repo URL (must come BEFORE email replacement to avoid corrupting git@gitlab...)
sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/infra/[a-zA-Z0-9_-]*\.git|${GIT_REPO_URL}|g" \
    "$TOFU_MODULES/gitlab-config/main.tf"
# ssh-keyscan host
sed -i "s|ssh-keyscan -p 2222 [a-zA-Z0-9._-]*|ssh-keyscan -p 2222 gitlab.${SUPPORT_DOMAIN}|" \
    "$TOFU_MODULES/gitlab-config/main.tf"
# Email addresses (exclude SSH URLs)
sed -i "/ssh:\/\//!s|@[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|@${BASE_DOMAIN}\"|g" \
    "$TOFU_MODULES/gitlab-config/main.tf"

# --- 8h. teleport-config — proxy-addr ---
sed -i "s|teleport\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*:3080|teleport.${SUPPORT_DOMAIN}:3080|g" \
    "$TOFU_MODULES/teleport-config/vault.tf"

# ============================================================================
# 9. Update ArgoCD Application files
# ============================================================================
echo "  Updating ArgoCD base Application files..."

# --- 9a. ArgoCD base Application files — repoURL ---
for f in "$PROJECT_ROOT"/iac/argocd/base/*.yaml; do
    [ -f "$f" ] || continue
    sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/infra/[a-zA-Z0-9_-]*\.git|${GIT_REPO_URL}|g" "$f"
done

# --- 9c. ArgoCD AppProject sourceRepos ---
for f in "$PROJECT_ROOT"/iac/argocd/projects/*.yaml; do
    [ -f "$f" ] || continue
    sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/infra/[a-zA-Z0-9_-]*\.git|${GIT_REPO_URL}|g" "$f"
    sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/apps/\*|ssh://git@gitlab.${SUPPORT_DOMAIN}:2222/apps/*|g" "$f"
done

# --- 9b. ArgoCD cluster Application + kustomize overlay files ---
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    ARGOCD_CLUSTER_DIR="$PROJECT_ROOT/iac/argocd/clusters/$CLUSTER"

    echo "  Updating ArgoCD cluster files for $CLUSTER..."

    # Process all YAML files in the cluster's ArgoCD directory (recursive)
    while IFS= read -r -d '' f; do
        # GitLab repoURL (SSH)
        sed -i "s|ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/infra/[a-zA-Z0-9_-]*\.git|${GIT_REPO_URL}|g" "$f"

        # GitLab API URL (in ApplicationSets)
        sed -i "s|api: https://gitlab\.[a-zA-Z0-9._-]*|api: ${GITLAB_URL}|g" "$f"

        # Harbor registry references (in image-updater annotations and image names)
        sed -i "s|harbor\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*/|harbor.${SUPPORT_DOMAIN}/|g" "$f"

        # Portal annotation prefix
        sed -i "s|portal\.[a-zA-Z0-9._-]*/|${PORTAL_PREFIX}/|g" "$f"

        # Support VM service domains in kustomize overlays
        for svc in vault harbor minio minio-console idp gitlab zac keycloak teleport; do
            sed -i "s|${svc}\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${svc}.${SUPPORT_DOMAIN}|g" "$f"
        done

        # Cluster-specific service domains (match: SERVICE.CLUSTER.old.domain → SERVICE.CLUSTER_DOMAIN)
        # Wildcard domains: *.kss.old.domain → *.CLUSTER_DOMAIN
        sed -i "s|\*\.${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\*.${CDOMAIN}|g" "$f"
        # Service subdomains: service.kss.old.domain → service.CLUSTER_DOMAIN
        sed -i "s|\([a-zA-Z0-9_-]*\)\.${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\1.${CDOMAIN}|g" "$f"
        # Bare cluster domain (e.g., value: "kss.example.com")
        sed -i "s|\"${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|\"${CDOMAIN}\"|g" "$f"

        # Unquoted bare cluster domain (e.g., value: kss.example.com)
        sed -i "s|: ${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*$|: ${CDOMAIN}|g" "$f"

        # Domain slugs in cert/secret names (e.g., wildcard-kcs-example-com-tls)
        DSLUG=$(domain_slug "$CDOMAIN")
        sed -i "s|wildcard-${CLUSTER}-[a-z0-9-]*[a-z]-tls|wildcard-${DSLUG}-tls|g" "$f"
        sed -i "s|wildcard-${CLUSTER}-[a-z0-9-]*[a-z]\([^a-z0-9-]\)|wildcard-${DSLUG}\1|g" "$f"
        sed -i "s|wildcard-${CLUSTER}-[a-z0-9-]*[a-z]$|wildcard-${DSLUG}|g" "$f"

        # cert-manager: email and dnsZones (root domain)
        sed -i "s|email: letsencrypt@[a-zA-Z0-9._-]*|email: ${LETSENCRYPT_EMAIL}|g" "$f"
        sed -i "/dnsZones:/{ n; s|            - [a-zA-Z0-9._-]*|            - ${ROOT_DOMAIN}| }" "$f"
        # cert-manager comments referencing root domain
        sed -i "s|domain in [a-zA-Z0-9._-]*$|domain in ${ROOT_DOMAIN}|g" "$f"
        sed -i "s|solver for [a-zA-Z0-9._-]* domain|solver for ${ROOT_DOMAIN} domain|g" "$f"

        # Comments with support domain patterns
        sed -i "s|\*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\*.${SUPPORT_DOMAIN}|g" "$f"

    done < <(find "$ARGOCD_CLUSTER_DIR" -name '*.yaml' -print0)
done

# ============================================================================
# 10. Update NixOS acme.nix virtual host attribute names
# ============================================================================
echo "  Updating NixOS acme.nix..."

ACME_NIX="$PROJECT_ROOT/iac/provision/nix/supporting-systems/modules/acme.nix"
if [ -f "$ACME_NIX" ]; then
    for svc in vault minio minio-console harbor idp gitlab teleport zac; do
        sed -i "s|\"${svc}\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|\"${svc}.${SUPPORT_DOMAIN}\"|g" "$ACME_NIX"
    done
fi

# ============================================================================
# 11. Update scripts with hardcoded values
# ============================================================================
echo "  Updating scripts..."

# scripts/hypervisor-exec.sh — if it exists
if [ -f "$PROJECT_ROOT/scripts/hypervisor-exec.sh" ]; then
    sed -i "s|REMOTE_HOST=\"[a-zA-Z0-9._-]*\"|REMOTE_HOST=\"${HYPERVISOR}\"|" \
        "$PROJECT_ROOT/scripts/hypervisor-exec.sh"
    sed -i "s|REMOTE_PROJECT_DIR=\"[^\"]*\"|REMOTE_PROJECT_DIR=\"${REMOTE_PROJECT_DIR}\"|" \
        "$PROJECT_ROOT/scripts/hypervisor-exec.sh"
fi

# scripts/iter-exec.sh — if it exists (legacy name)
if [ -f "$PROJECT_ROOT/scripts/iter-exec.sh" ]; then
    sed -i "s|REMOTE_HOST=\"[a-zA-Z0-9._-]*\"|REMOTE_HOST=\"${HYPERVISOR}\"|" \
        "$PROJECT_ROOT/scripts/iter-exec.sh"
    sed -i "s|REMOTE_PROJECT_DIR=\"[^\"]*\"|REMOTE_PROJECT_DIR=\"${REMOTE_PROJECT_DIR}\"|" \
        "$PROJECT_ROOT/scripts/iter-exec.sh"
fi

# --- 11a. stages/4_bootstrap/bootstrap-argocd.sh ---
BOOTSTRAP_ARGOCD="$PROJECT_ROOT/stages/4_bootstrap/bootstrap-argocd.sh"
if [ -f "$BOOTSTRAP_ARGOCD" ]; then
    sed -i "s|GITLAB_SSH_URL=\"ssh://git@gitlab\.[a-zA-Z0-9._-]*:2222/infra/[a-zA-Z0-9_-]*\.git\"|GITLAB_SSH_URL=\"${GIT_REPO_URL}\"|" "$BOOTSTRAP_ARGOCD"
    sed -i "s|VAULT_ADDR:-https://vault\.[a-zA-Z0-9._-]*|VAULT_ADDR:-${VAULT_URL}|" "$BOOTSTRAP_ARGOCD"
fi

# --- 11b. scripts/harbor-login.sh ---
HARBOR_LOGIN="$PROJECT_ROOT/scripts/harbor-login.sh"
if [ -f "$HARBOR_LOGIN" ]; then
    sed -i "s|HARBOR_REGISTRY=\"harbor\.[a-zA-Z0-9._-]*\"|HARBOR_REGISTRY=\"harbor.${SUPPORT_DOMAIN}\"|" "$HARBOR_LOGIN"
    sed -i "s|VAULT_URL=\"https://vault\.[a-zA-Z0-9._-]*\"|VAULT_URL=\"${VAULT_URL}\"|" "$HARBOR_LOGIN"
fi

# --- 11c. iac/scripts/*.sh ---
for f in "$PROJECT_ROOT"/iac/scripts/*.sh; do
    [ -f "$f" ] || continue
    # Vault address in usage comments and defaults
    sed -i "s|VAULT_ADDR=https://vault\.[a-zA-Z0-9._-]*|VAULT_ADDR=${VAULT_URL}|g" "$f"
    sed -i "s|export VAULT_ADDR=https://vault\.[a-zA-Z0-9._-]*|export VAULT_ADDR=${VAULT_URL}|g" "$f"
    # SPIRE OIDC URL and trust domain defaults
    sed -i "s|SPIRE_OIDC_URL:-https://spire-oidc\.[a-zA-Z0-9._-]*}|SPIRE_OIDC_URL:-https://spire-oidc.kss.${BASE_DOMAIN}}|" "$f"
    sed -i "s|TRUST_DOMAIN:-[a-zA-Z0-9._-]*}|TRUST_DOMAIN:-kss.${BASE_DOMAIN}}|" "$f"
    # PKI role in policy JSON
    sed -i "s|pki_int/issue/overkill|pki_int/issue/${SUPPORT_PREFIX}|g" "$f"
done

# --- 11d. tofu/scripts/*.sh ---
for f in "$PROJECT_ROOT"/tofu/scripts/*.sh; do
    [ -f "$f" ] || continue
    # Vault fallback defaults
    sed -i "s|TF_VAR_vault_addr:-https://vault\.[a-zA-Z0-9._-]*|TF_VAR_vault_addr:-${VAULT_URL}|g" "$f"
    # Keycloak fallback defaults
    sed -i "s|TF_VAR_keycloak_url:-https://idp\.[a-zA-Z0-9._-]*|TF_VAR_keycloak_url:-${KEYCLOAK_URL}|g" "$f"
    # GitLab fallback defaults
    sed -i "s|TF_VAR_gitlab_url:-https://gitlab\.[a-zA-Z0-9._-]*|TF_VAR_gitlab_url:-${GITLAB_URL}|g" "$f"
    # Harbor fallback defaults
    sed -i "s|TF_VAR_harbor_url:-https://harbor\.[a-zA-Z0-9._-]*|TF_VAR_harbor_url:-${HARBOR_URL}|g" "$f"
    # MinIO URL in mcli alias
    sed -i "s|https://minio\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${MINIO_URL}|g" "$f"
done

# --- 11e. NixOS support VM reference scripts ---
SUPPORT_SCRIPTS="$PROJECT_ROOT/iac/provision/nix/supporting-systems/scripts"
if [ -d "$SUPPORT_SCRIPTS" ]; then
    for f in "$SUPPORT_SCRIPTS"/*.sh; do
        [ -f "$f" ] || continue
        # Domain references
        for svc in vault harbor minio minio-console idp gitlab teleport zac; do
            sed -i "s|${svc}\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${svc}.${SUPPORT_DOMAIN}|g" "$f"
        done
        # Bare domain (DOMAIN="old.domain")
        sed -i "s|DOMAIN=\"[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*\"|DOMAIN=\"${SUPPORT_DOMAIN}\"|" "$f"
        # Wildcard comment patterns
        sed -i "s|\*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\*.${SUPPORT_DOMAIN}|g" "$f"
        # PKI role name and issue path
        sed -i "s|pki_int/roles/[a-zA-Z0-9_-]*|pki_int/roles/${SUPPORT_PREFIX}|g" "$f"
        sed -i "s|pki_int/issue/[a-zA-Z0-9_-]*|pki_int/issue/${SUPPORT_PREFIX}|g" "$f"
        # allowed_domains in vault write commands
        sed -i "s|allowed_domains=\"[^\"]*\"|allowed_domains=\"${SUPPORT_DOMAIN},${BASE_DOMAIN}\"|g" "$f"
        # Echo with role name
        sed -i "s|Role '[a-zA-Z0-9_-]*' created|Role '${SUPPORT_PREFIX}' created|g" "$f"
        # common_name examples
        sed -i "s|common_name=myservice\.[a-zA-Z0-9._-]*|common_name=myservice.${SUPPORT_DOMAIN}|g" "$f"
    done
fi

# --- 11f. Kustomize base: gateway, cert-manager wildcard/reference-grant ---
# Gateway files — wildcard hostname and cert secret name
GATEWAY_DIR="$KUSTOMIZE_BASE/gateway"
if [ -d "$GATEWAY_DIR" ]; then
    DSLUG=$(domain_slug "$SUPPORT_DOMAIN")
    for f in "$GATEWAY_DIR"/*.yaml; do
        [ -f "$f" ] || continue
        sed -i "s|\*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\*.${SUPPORT_DOMAIN}|g" "$f"
        sed -i "s|wildcard-[a-z0-9-]*[a-z]-tls|wildcard-${DSLUG}-tls|g" "$f"
        # Example HTTPRoute hostnames
        sed -i "s|example\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|example.${SUPPORT_DOMAIN}|g" "$f"
    done
fi

# cert-manager wildcard certificate
CERT_DIR="$KUSTOMIZE_BASE/cert-manager"
if [ -d "$CERT_DIR" ]; then
    DSLUG=$(domain_slug "$SUPPORT_DOMAIN")
    # wildcard-certificate.yaml
    WILDCARD_CERT="$CERT_DIR/wildcard-certificate.yaml"
    if [ -f "$WILDCARD_CERT" ]; then
        sed -i "s|wildcard-[a-z0-9-]*[a-z]-tls|wildcard-${DSLUG}-tls|g" "$WILDCARD_CERT"
        sed -i "s|wildcard-[a-z0-9-]*[a-z]\([^a-z0-9-]\)|wildcard-${DSLUG}\1|g" "$WILDCARD_CERT"
        sed -i "s|wildcard-[a-z0-9-]*[a-z]$|wildcard-${DSLUG}|g" "$WILDCARD_CERT"
        sed -i "s|\*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\*.${SUPPORT_DOMAIN}|g" "$WILDCARD_CERT"
        sed -i "s|\"[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*\"$|\"${SUPPORT_DOMAIN}\"|" "$WILDCARD_CERT"
    fi
    # reference-grant.yaml — cert secret name
    REF_GRANT="$CERT_DIR/reference-grant.yaml"
    if [ -f "$REF_GRANT" ]; then
        sed -i "s|wildcard-[a-z0-9-]*[a-z]-tls|wildcard-${DSLUG}-tls|g" "$REF_GRANT"
    fi
fi

# --- 11f2. Remaining scripts with domain examples in comments ---
for f in "$PROJECT_ROOT/scripts/fix-keycloak-scopes.sh" "$PROJECT_ROOT/scripts/generate-cluster.sh"; do
    [ -f "$f" ] || continue
    for CLUSTER in $(get_clusters); do
        CDOMAIN=$(cluster_domain "$CLUSTER")
        sed -i "s|${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${CDOMAIN}|g" "$f"
    done
done

# --- 11g. Demo files ---
DEMO_DIR="$PROJECT_ROOT/iac/demo"
if [ -d "$DEMO_DIR" ]; then
    for f in "$DEMO_DIR"/*.yaml; do
        [ -f "$f" ] || continue
        for CLUSTER in $(get_clusters); do
            CDOMAIN=$(cluster_domain "$CLUSTER")
            sed -i "s|\([a-zA-Z0-9_-]*\)\.${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|\1.${CDOMAIN}|g" "$f"
        done
    done
fi

# --- 11h. generic-app chart values ---
# generic-app chart — Harbor registry, portal prefix, and cluster domain in comments
GENERIC_APP="$PROJECT_ROOT/iac/argocd/charts/generic-app/values.yaml"
if [ -f "$GENERIC_APP" ]; then
    sed -i "s|harbor\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|harbor.${SUPPORT_DOMAIN}|g" "$GENERIC_APP"
    sed -i "s|portal\.[a-zA-Z0-9._-]*/|${PORTAL_PREFIX}/|g" "$GENERIC_APP"
    # Cluster domain in comments (use first cluster as example)
    for CLUSTER in $(get_clusters); do
        CDOMAIN=$(cluster_domain "$CLUSTER")
        sed -i "s|${CLUSTER}\.[a-zA-Z0-9._-]*\.[a-zA-Z]*|${CDOMAIN}|g" "$GENERIC_APP"
    done
fi

# App build-push scripts — Harbor registry
for f in "$PROJECT_ROOT"/iac/apps/*/build-push.sh; do
    [ -f "$f" ] || continue
    sed -i "s|REGISTRY=\"harbor\.[a-zA-Z0-9._-]*\"|REGISTRY=\"harbor.${SUPPORT_DOMAIN}\"|" "$f"
done

# ============================================================================
# Done
# ============================================================================

echo ""
echo "Configuration generated successfully!"
echo ""
echo "Generated files:"
echo "  stages/lib/config-local.sh"
echo "  iac/provision/nix/supporting-systems/generated-config.nix"
echo "  tofu/environments/*/terraform.tfvars"
echo ""
echo "Updated files:"
echo "  iac/clusters/*/cluster.yaml"
echo "  iac/argocd/base/*.yaml"
echo "  iac/argocd/clusters/*/*.yaml"
echo "  iac/argocd/clusters/*/kustomize/**/*.yaml"
echo "  iac/argocd/values/{base,kss,kcs}/*.yaml"
echo "  iac/kustomize/base/*"
echo "  iac/provision/nix/supporting-systems/modules/acme.nix"
echo "  tofu/environments/*/{backend,providers,variables}.tf"
echo "  tofu/modules/*/*.tf"
echo ""
echo "Next steps:"
echo "  1. Run 'just generate' to regenerate cluster overlays"
echo "  2. Review changes with 'git diff'"
echo "  3. Commit and push to GitLab"
