#!/usr/bin/env bash
# Generate local configuration from config.yaml
#
# Reads config.yaml and produces ONLY gitignored files:
#   - stages/lib/config-local.sh                       (shell variables)
#   - iac/provision/nix/supporting-systems/generated-config.nix
#   - tofu/environments/*/terraform.tfvars              (OpenTofu variables)
#   - tofu/environments/*/backend.tf                    (MinIO S3 backend)
#   - .push-guard                                       (pre-push hook patterns)
#
# No tracked files are modified — safe to run on the main branch at any time.
#
# Usage: ./scripts/generate-config.sh [--check]
#   --check: verify config.yaml exists without generating

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/config.yaml"

# ─── Preflight ───────────────────────────────────────────────────────────────

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE not found."
    echo "Copy config.yaml.example to config.yaml and fill in your values:"
    echo "  cp config.yaml.example config.yaml"
    exit 1
fi

if ! command -v yq &>/dev/null; then
    echo "ERROR: yq is required but not found. Run: nix develop"
    exit 1
fi

if [ "${1:-}" = "--check" ]; then
    echo "config.yaml found and valid."
    exit 0
fi

# ─── Read config.yaml ────────────────────────────────────────────────────────

cfg() { yq -r "$1" "$CONFIG_FILE"; }

ROOT_DOMAIN=$(cfg '.domains.root')
BASE_DOMAIN=$(cfg '.domains.base')
SUPPORT_PREFIX=$(cfg '.domains.support_prefix')
ZITI_DOMAIN=$(cfg '.domains.ziti')

SUPPORT_IP=$(cfg '.support.ip')
TELEPORT_CLUSTER_NAME=$(cfg '.support.teleport_cluster_name')

ADMIN_EMAIL=$(cfg '.identity.admin_email')

NFS_ALLOWED_NETWORK=$(cfg '.network.nfs_allowed_network')
GATEWAY_IP=$(cfg '.network.gateway_ip // "10.69.50.1"')
MANAGEMENT_CIDR=$(cfg '.network.management_cidr // "10.69.10.0/24"')
POD_CIDR=$(cfg '.network.pod_cidr // "10.42.0.0/16"')

GIT_PROJECT_NAME=$(cfg '.git.project_name')
GITHUB_ORG=$(cfg '.git.github_org')

# ─── Derived values ──────────────────────────────────────────────────────────

SUPPORT_DOMAIN="${SUPPORT_PREFIX}.${BASE_DOMAIN}"
VAULT_URL="https://vault.${SUPPORT_DOMAIN}"
HARBOR_URL="https://harbor.${SUPPORT_DOMAIN}"
HARBOR_REGISTRY="harbor.${SUPPORT_DOMAIN}"
MINIO_URL="https://minio.${SUPPORT_DOMAIN}"
GITLAB_URL="https://gitlab.${SUPPORT_DOMAIN}"
GITLAB_SSH_URL="ssh://git@gitlab.${SUPPORT_DOMAIN}:2222"
GIT_REPO_URL="ssh://git@gitlab.${SUPPORT_DOMAIN}:2222/infra/${GIT_PROJECT_NAME}.git"
KEYCLOAK_URL="https://idp.${SUPPORT_DOMAIN}"
TELEPORT_ADDR="teleport.${SUPPORT_DOMAIN}:3080"
LETSENCRYPT_EMAIL="letsencrypt@${ROOT_DOMAIN}"
PORTAL_PREFIX="portal.homelab"
GITLAB_SSH_HOST="[gitlab.${SUPPORT_DOMAIN}]:2222"
TARGET_REVISION="deploy"

echo "Generating config from $CONFIG_FILE..."
echo "  Root domain:    $ROOT_DOMAIN"
echo "  Base domain:    $BASE_DOMAIN"
echo "  Support domain: $SUPPORT_DOMAIN"

# ─── Helper: discover clusters ────────────────────────────────────────────────

get_clusters() {
    local clusters=()
    for dir in "$PROJECT_ROOT"/iac/clusters/*/; do
        if [ -f "${dir}cluster.yaml" ]; then
            clusters+=("$(basename "$dir")")
        fi
    done
    echo "${clusters[@]}"
}

cluster_domain() { echo "${1}.${BASE_DOMAIN}"; }

# ============================================================================
# 1. Generate stages/lib/config-local.sh
# ============================================================================
echo "  Generating stages/lib/config-local.sh..."
cat > "$PROJECT_ROOT/stages/lib/config-local.sh" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml

SUPPORT_VM_IP="$SUPPORT_IP"
SUPPORT_DOMAIN="$SUPPORT_DOMAIN"
ROOT_DOMAIN="$ROOT_DOMAIN"
BASE_DOMAIN="$BASE_DOMAIN"
VAULT_URL="$VAULT_URL"
HARBOR_URL="$HARBOR_URL"
HARBOR_REGISTRY="$HARBOR_REGISTRY"
MINIO_URL="$MINIO_URL"
GITLAB_URL="$GITLAB_URL"
GITLAB_SSH_URL="$GITLAB_SSH_URL"
GIT_REPO_URL="$GIT_REPO_URL"
KEYCLOAK_URL="$KEYCLOAK_URL"
TELEPORT_ADDR="$TELEPORT_ADDR"
PORTAL_PREFIX="$PORTAL_PREFIX"
NFS_ALLOWED_NETWORK="$NFS_ALLOWED_NETWORK"
GATEWAY_IP="$GATEWAY_IP"
MANAGEMENT_CIDR="$MANAGEMENT_CIDR"
POD_CIDR="$POD_CIDR"
LETSENCRYPT_EMAIL="$LETSENCRYPT_EMAIL"
SUPPORT_PREFIX="$SUPPORT_PREFIX"
ZITI_DOMAIN="$ZITI_DOMAIN"
TARGET_REVISION="$TARGET_REVISION"
EOF

# ============================================================================
# 2. Generate NixOS config
# ============================================================================
echo "  Generating generated-config.nix..."
cat > "$PROJECT_ROOT/iac/provision/nix/supporting-systems/generated-config.nix" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
# Source: config.yaml
{
  domain = "${SUPPORT_DOMAIN}";
  rootDomain = "${ROOT_DOMAIN}";
  baseDomain = "${BASE_DOMAIN}";
  supportPrefix = "${SUPPORT_PREFIX}";
  zitiDomain = "${ZITI_DOMAIN}";
  adminEmail = "${ADMIN_EMAIL}";
  supportIp = "${SUPPORT_IP}";
  teleportClusterName = "${TELEPORT_CLUSTER_NAME}";
  githubOrg = "${GITHUB_ORG}";
  gitProjectName = "${GIT_PROJECT_NAME}";
  gitlabSshHost = "${GITLAB_SSH_HOST}";
  harborRegistry = "${HARBOR_REGISTRY}";
  nfsAllowedNetwork = "${NFS_ALLOWED_NETWORK}";
}
EOF

# ============================================================================
# 3. Generate OpenTofu terraform.tfvars
# ============================================================================
echo "  Generating tofu/environments/*/terraform.tfvars..."

# base/terraform.tfvars
cat > "$PROJECT_ROOT/tofu/environments/base/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr       = "${VAULT_URL}"
keycloak_url     = "${KEYCLOAK_URL}"
minio_endpoint   = "minio.${SUPPORT_DOMAIN}"
gitlab_url       = "${GITLAB_URL}"
ziti_api_url     = "https://${ZITI_DOMAIN}:2029/edge/management/v1"
teleport_addr    = "${TELEPORT_ADDR}"
harbor_url       = "${HARBOR_URL}"
base_domain             = "${BASE_DOMAIN}"
support_domain          = "${SUPPORT_DOMAIN}"
email_domain            = "${BASE_DOMAIN}"
cluster_names           = ["$(echo "$(get_clusters)" | sed 's/ /", "/g')"]
EOF

# Append extra_users from config.yaml identity.users
{
  echo ""
  echo "extra_users = ["
  yq -r '.identity.users // [] | .[] | "  { username = \"" + .username + "\", email = \"" + .email + "\", first_name = \"" + .first_name + "\", last_name = \"" + .last_name + "\", role = \"" + .role + "\" },"' "$CONFIG_FILE" 2>/dev/null || true
  echo "]"

  echo ""
  echo "ziti_client_devices = {"
  yq -r '.ziti.client_devices // [] | .[] | "  \"" + .name + "\" = { role_attributes = [" + ([.role_attributes[] | "\"" + . + "\""] | join(", ")) + "] },"' "$CONFIG_FILE" 2>/dev/null || true
  echo "}"
} >> "$PROJECT_ROOT/tofu/environments/base/terraform.tfvars"

# Per-cluster tfvars
for CLUSTER in $(get_clusters); do
    CDOMAIN=$(cluster_domain "$CLUSTER")
    cat > "$PROJECT_ROOT/tofu/environments/$CLUSTER/terraform.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr          = "${VAULT_URL}"
harbor_url          = "${HARBOR_URL}"
broker_keycloak_url = "https://auth.${CDOMAIN}"
base_domain         = "${BASE_DOMAIN}"
support_domain      = "${SUPPORT_DOMAIN}"
EOF
done

# dependencytrack/terraform.tfvars — per-cluster, generated at apply time
# Only generate a placeholder; actual values are passed via just tofu-dtrack <cluster>
for CLUSTER in $(get_clusters); do
    CDOMAIN="${CLUSTER}.${BASE_DOMAIN}"
    cat > "$PROJECT_ROOT/tofu/environments/dependencytrack/terraform-${CLUSTER}.tfvars" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
vault_addr              = "${VAULT_URL}"
dependencytrack_url     = "https://dtrack.${CDOMAIN}"
cluster_name            = "${CLUSTER}"
EOF
done

# ============================================================================
# 5. Generate OpenTofu backend.tf
# ============================================================================
echo "  Generating tofu/environments/*/backend.tf..."

generate_backend() {
    local env="$1" key="$2"
    cat > "$PROJECT_ROOT/tofu/environments/$env/backend.tf" << EOF
# Auto-generated by scripts/generate-config.sh — do not edit
terraform {
  backend "s3" {
    bucket = "tofu-state"
    key    = "${key}/terraform.tfstate"
    region = "us-east-1"

    # MinIO S3-compatible backend
    endpoints = {
      s3 = "${MINIO_URL}"
    }

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_path_style              = true
  }
}
EOF
}

generate_backend "base" "base"
# dependencytrack backend uses -backend-config=key=... at init time (per-cluster)
generate_backend "dependencytrack" "dependencytrack-CLUSTER"
for CLUSTER in $(get_clusters); do
    generate_backend "$CLUSTER" "$CLUSTER"
done

# ============================================================================
# 6. Generate .push-guard (patterns for pre-push hook)
# ============================================================================
echo "  Generating .push-guard..."
cat > "$PROJECT_ROOT/.push-guard" << EOF
# Personal domain patterns — blocked from GitHub pushes
# Used by .githooks/pre-push
${SUPPORT_DOMAIN}
${BASE_DOMAIN}
${ROOT_DOMAIN}
${ZITI_DOMAIN}
${ADMIN_EMAIL}
EOF

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "Config generated successfully."
echo ""
echo "Generated files (gitignored on main):"
echo "  stages/lib/config-local.sh"
echo "  iac/provision/nix/supporting-systems/generated-config.nix"
echo "  tofu/environments/*/terraform.tfvars"
echo "  tofu/environments/*/backend.tf"
echo "  .push-guard"
echo ""
echo "Next: run 'just generate' to generate per-cluster configs."
