apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/architecture

patches:
  - target:
      kind: Deployment
      name: architecture
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: harbor.support.example.com/kss/architecture:latest
  - target:
      kind: Ingress
      name: architecture
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: architecture.simple-k8s.example.com
      - op: replace
        path: /spec/rules/0/host
        value: architecture.simple-k8s.example.com
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1auth-signin
        value: "https://oauth2-proxy.simple-k8s.example.com/oauth2/start?rd=$scheme://$host$escaped_request_uri"
