# CiliumBGPAdvertisement for kcs cluster
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: kcs-advertise-lb
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: never-used-key
            operator: NotIn
            values: ["never-used-value"]
