# CiliumBGPClusterConfig for kcs cluster
# localASN 64513, peer router 10.69.50.1 ASN 64512
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: kcs-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp_enabled: "true"
  bgpInstances:
    - name: "instance-64513"
      localASN: 64513
      peers:
        - name: "peer-64512-unifi"
          peerAddress: "10.69.50.1"
          peerASN: 64512
          peerConfigRef:
            name: "kcs-peer"
