# CiliumLoadBalancerIPPool for kcs cluster
# Uses 10.69.50.208/28 (10.69.50.208-223) for LoadBalancer VIPs
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: kcs-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.69.50.208/28"
  serviceSelector:
    matchExpressions:
      - key: never-used-key
        operator: NotIn
        values: ["never-used-value"]
