apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../kustomize/base/architecture

patches:
  # Delete Ingress on kcs (uses Gateway API HTTPRoute instead)
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: architecture
        namespace: kube-public
      $patch: delete
