apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform operators and monitoring (waves 0, 2, 3)
  sourceRepos:
    - https://github.com/example-user/homelab.git
    - https://argoproj.github.io/argo-helm
    - https://charts.longhorn.io
    - https://open-policy-agent.github.io/gatekeeper/charts
    - https://spiffe.github.io/helm-charts-hardened
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://aquasecurity.github.io/helm-charts
    - https://cloudnative-pg.github.io/charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: trivy-system
    - server: https://kubernetes.default.svc
      namespace: gatekeeper-system
    - server: https://kubernetes.default.svc
      namespace: spire-system
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: kube-system
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: templates.gatekeeper.sh
      kind: ConstraintTemplate
    - group: constraints.gatekeeper.sh
      kind: "*"
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: ""
      kind: Namespace
    - group: monitoring.coreos.com
      kind: "*"
    - group: spire.spiffe.io
      kind: ClusterSPIFFEID
    - group: scheduling.k8s.io
      kind: PriorityClass
    - group: storage.k8s.io
      kind: CSIDriver
    - group: aquasecurity.github.io
      kind: "*"
