# -*- mode: ruby -*-
# vi: set ft=ruby :

# MAC address assignments for VLAN 50 interface
# Pattern: 52:54:00:69:50:XX (52:54:00 = libvirt prefix, 69:50 = VLAN 50)
# Configure these as static DHCP leases in Unifi with corresponding hostnames
MAC_ADDRESSES = {
  "support"      => "52:54:00:69:50:10",
  "k8s-master"   => "52:54:00:69:50:20",
  "k8s-worker-1" => "52:54:00:69:50:31",
  "k8s-worker-2" => "52:54:00:69:50:32",
  "k8s-worker-3" => "52:54:00:69:50:33",
}

Vagrant.configure("2") do |config|
  # Base configuration for all boxes
  # Using local NixOS qcow image with libvirt
  config.vm.box = "local/nixos-25.11-vagrant"
  config.vm.box_url = "file://#{File.expand_path(File.dirname(__FILE__))}/nixos-25.11-vagrant.box"

  # SSH configuration - use custom ECDSA key instead of insecure key
  config.ssh.private_key_path = File.expand_path("~/.vagrant.d/ecdsa_private_key")
  config.ssh.insert_key = false
  # Prevent terminal escape sequences from corrupting Vagrant commands
  config.ssh.shell = "TERM=dumb bash -l"
  # Disable Vagrant's hostname setting - NixOS box doesn't have /etc/nixos structure
  # Hostname is set via NixOS configuration
  config.vm.hostname = nil

  # Shared folder configuration - disabled for NixOS
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Prevent Vagrant from modifying /etc/fstab (read-only on NixOS)
  config.vm.allow_fstab_modification = false

  # Default provider: libvirt with KVM (for Arch Linux)
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.graphics_type = "spice"
    libvirt.graphics_port = -1
    libvirt.graphics_autoport = true
    libvirt.qemu_use_session = false
    # Disable QEMU guest agent (we use DHCP for IP, not agent queries)
    libvirt.qemu_use_agent = false
  end

  # Set libvirt as the default provider
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

  # Supporting Systems VM
  # Hosts: Vault, Harbor, MinIO, NFS
  config.vm.define "support" do |support|
    support.vm.network :public_network,
      dev: "br-k8s",
      mode: "bridge",
      type: "bridge",
      mac: MAC_ADDRESSES["support"],
      auto_config: false

    support.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
      libvirt.disk_bus = "virtio"
      libvirt.disk_driver :cache => "directsync"
      libvirt.cpu_mode = "host-passthrough"
    end
  end

  # Kubernetes Master Node
  config.vm.define "k8s-master" do |master|
    master.vm.network :public_network,
      dev: "br-k8s",
      mode: "bridge",
      type: "bridge",
      mac: MAC_ADDRESSES["k8s-master"],
      auto_config: false

    master.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
      libvirt.disk_bus = "virtio"
      libvirt.disk_driver :cache => "directsync"
      libvirt.cpu_mode = "host-passthrough"
    end
  end

  # Kubernetes Worker Nodes (3x)
  (1..3).each do |i|
    config.vm.define "k8s-worker-#{i}" do |worker|
      worker.vm.network :public_network,
        dev: "br-k8s",
        mode: "bridge",
        type: "bridge",
        mac: MAC_ADDRESSES["k8s-worker-#{i}"],
        auto_config: false

      worker.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 4
        libvirt.disk_bus = "virtio"
        libvirt.disk_driver :cache => "directsync"
        libvirt.cpu_mode = "host-passthrough"
      end
    end
  end
end
