apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beyla
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/example-user/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: beyla
      targetRevision: "1.*"
      helm:
        valueFiles:
          - $values/iac/argocd/values/base/beyla.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: beyla-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
