apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/example-user/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://open-policy-agent.github.io/gatekeeper/charts
      chart: gatekeeper
      targetRevision: "3.21.*"
      helm:
        valueFiles:
          - $values/iac/argocd/values/base/gatekeeper.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.preserveUnknownFields
        - .spec.conversion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
