apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-terminal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: applications
  source:
    repoURL: https://github.com/example-user/homelab.git
    targetRevision: main
    path: iac/kustomize/base/open-terminal
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
