apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd-image-updater.argoproj.io/image-list: "app=ghcr.io/open-webui/open-webui"
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.allow-tags: "regexp:^\\d+\\.\\d+\\.\\d+$"
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: applications
  sources:
    - repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: "12.*"
      helm:
        valueFiles:
          - $values/iac/argocd/values/base/open-webui.yaml
          - $values/iac/argocd/values/CLUSTER_NAME/open-webui.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
