apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spire
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/example-user/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://spiffe.github.io/helm-charts-hardened
      chart: spire-crds
      targetRevision: "0.5.*"
    - repoURL: https://spiffe.github.io/helm-charts-hardened
      chart: spire
      targetRevision: "0.28.*"
      helm:
        valueFiles:
          - $values/iac/argocd/values/base/spire.yaml
          - $values/iac/argocd/values/CLUSTER_NAME/spire.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spire-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
