apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: bootstrap
  source:
    repoURL: ssh://git@gitlab.support.example.com:2222/infra/homelab.git
    targetRevision: main
    path: iac/kustomize/base/vault-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
