apiVersion: v1
kind: Service
metadata:
  name: open-terminal
  namespace: open-webui
spec:
  selector:
    app.kubernetes.io/name: open-terminal
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
